### ISSUE TITLE
Terminal output misaligned

### ISSUE THREAD

**Issue by 94noni** [symfony-cli/symfony-cli#10]
There is a misalign on the table output for `symfony server:list`

Please see screenshot
<img width="1313" alt="Capture d’écran 2022-01-01 à 13 35 19" src="https://user-images.githubusercontent.com/1358361/147850688-aa096fa5-76b8-4146-91ac-bbe3772bce44.png">

I've not tested all commands,
Also I am not fluent with Go, so for now I am "unable" to try to fix it :)
Thanks

---

On macOS 12.1 (21C52)

```bash
symfony version
Symfony CLI version 5.0.4 (c) 2017-2022 Symfony SAS (2022-01-01T10:25:37Z - stable)
```

**Comment by Surfoo** [comment]
symfony-cli generate a hyperlink for the port, but the package tablewriter doesn't handle them in automatic padding and count the whole string, not only the text `8000`. 
Here a test : https://go.dev/play/p/P6M-6O8dtqu and the same code on my terminal :  
![test](https://user-images.githubusercontent.com/553659/147862735-a1f61d86-e4f5-4c1e-8483-cc70998950e9.png)

A quick fix should be to remove the link in symfony-cli. A better solution might be to fix the problem in the tablewriter package (not me)

**Comment by 94noni** [comment]
@Surfoo ho I didn't saw this on mine (macOS Terminal.app)
Indeed it could have gave a clue before :), I ll see if I can play with this binary locally and improve it

**Comment by Surfoo** [comment]
You could remove the link on the port and add a column with only the hyperlink without the href formatter.
