### ISSUE TITLE
symfony server:status and server:stop may be broken

### ISSUE THREAD

**Issue by kinekt4** [symfony-cli/symfony-cli#100]
Hi Devs,

I can start server but checking status or stopping server results in error because it thinks server hasn't started yet.

Start: `symfony server:start -d --dir=public/`

    [OK] Web server listening

Status: `symfony server:status`

    Local Web Server Not Running

Stop: `symfony server:stop`

    [OK] The web server is not running

Am I doing something wrong, or is there something broken. Thanks

***
**Environment**
OS: Fedora 35
PHP: 8.1
symfony-cli: v5.4.1

**Comment by fabpot** [comment]
Try to run the server with ou ``-d`` to see of there are any errors. If status says it's not running, it's probably because the server started and stopped immediately because of an error.

**Comment by kinekt4** [comment]
I forgot to mention that running start again: `symfony server:start -d --dir=public/` results in the following:

    [WARNING] The local web server is already running
