### ISSUE TITLE
Symfony starts server on different port than passed via `--port` argument

### ISSUE THREAD

**Issue by ruudk** [symfony-cli/symfony-cli#102]
I'm starting the server by passing `--port=60201` but notice that it listens on `60202`.

```
$ symfony server:start -d --no-tls --port=60201

 [WARNING] The local web server is optimized for local development and MUST never be used in a production setup.

 [OK] Web server listening
      The Web server is using PHP FPM 8.0.16
      http://127.0.0.1:60202/

Stream the logs via symfony server:log
```

After [inspecting the source code](https://github.com/symfony-cli/symfony-cli/blob/d96ec9fd450f255b7d7ce89e055e290a1341748f/local/process/listener.go#L32-L61) I see that the `--port` is actually a `preferred port`. This is not what I expected at all. 

Even though I think it's clever, this is not what I asked for. I asked for a server running on port `60201`. 

If I then connect to `http://localhost:60201` I does not answer.

Would it be an idea to only do the auto discovery of a free port when the `--port` argument is not provided?

**Comment by fabpot** [comment]
That makes sense to me. Would you like to work on a PR?

**Comment by ruudk** [comment]
I'll create a PR.
