### ISSUE TITLE
Symfony server directory resolution issue

### ISSUE THREAD

**Issue by kinekt4** [symfony-cli/symfony-cli#104]
Symfony server doesn't know different paths may point to the same directory (eg. via symlinks)

Consider the following symfony server instances, where directory is the same but paths are different.

    symfony server:list
    +--------------------------------------+--------------------------------------+---------+
    |              Directory               |                 Port                 | Domains |
    +--------------------------------------+--------------------------------------+---------+
    | ~/github/guestbook_6.0-1             | 8000 |         |
    | ~/source-code/github/guestbook_6.0-1 | 8002 |         |
    +--------------------------------------+--------------------------------------+---------+

Let's go to each path and check server status.

**Server 1**

    # path1
    cd ~/github/guestbook_6.0-1
    /bin/pwd
    /home/<user>/source-code/github/guestbook_6.0-1
    symfony server:status

> Local Web Server
> Listening on https://127.0.0.1:8000

**Server 2**

    # path2
    cd ~/source-code/github/guestbook_6.0-1
    /bin/pwd
    /home/<user>/source-code/github/guestbook_6.0-1
    symfony server:status

> Local Web Server
> Listening on https://127.0.0.1:8002

This issue poses two problems (*):

* If server was started in `path1` and you're in `path2`, running `server:status` will not display the running server (and vice versa)
* Consequently, if server was started in `path1`, and you're in `path2`, running `server:start` will start another instance of the server in the same directory

(*) If we assume only one of the servers are active at any one time.

I don't think this is intended. What are your thoughts?

***
**Environment**
OS: Fedora 35
symfony-cli: v5.4.1

**Comment by fabpot** [comment]
I suppose we should normalize the path early on. Can you work on a PR to fix this?

**Comment by kinekt4** [comment]
I must say this is my first time with golang, so my confidence level is low. But I will have a look to see if I can give it a go.

**Comment by kinekt4** [comment]
I've got a fix in but running into this blocker atm:

https://github.com/distribution/distribution/issues/3590

v2.8.1 which is being released soon is meant to resolve it.

**Comment by kinekt4** [comment]
I was just thinking about this change and I think it will resolve one problem and it will introduce another.

* Resolve: Multiple server instances in one directory
* Introduce: Invisible server instance if user is in a symlinked directory (requiring user to run `symfony server:list` to check)

I don't know if this is satisfactory from a user perspective.
