### ISSUE TITLE
Append serverVersion to DATABASE_URL for local server

### ISSUE THREAD

**Issue by fbourigault** [symfony-cli/symfony-cli#108]
When using the local server, I noticed that the `serverVersion` parameter is not appended to the `DATABASE_URL` variable.

This would workaround an issue I encountered while running a functional test suite which failed because of too many opened connections.

I found that when I use `dmaicher/doctrine-test-bundle`, the way the connection is created open a connection to the database to get the server version (https://github.com/dmaicher/doctrine-test-bundle/blob/master/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/StaticConnectionFactory.php#L39).

If I set the server version in `doctrine.yaml`, I can workaround the issue but I would like to avoid such situation as I may run my app with different PostgreSQL versions.

It would be a nice addition to append the `serverVersion` parameter to `DATABASE_URL` when using the local server.

**Comment by tucksaun** [comment]
This could be nice, especially as the default recommendation is to specify the serverVersion in `.env`
Though I'm not entirely sure how we can do this.

We could try to extract the tag (and thus the version) from the image but this looks fragile to me...

Another option could be to extract the environment variables (PG and MySQL exposes their major version for example, MariaDB exposes the full version only) but it looks like the Docker library does not expose them for the containers 🤔 
And inspecting the image seems a bit overkill for that.

**Comment by alexander-schranz** [comment]
It is really strange behaviour that it even overrides defined `.env.local` parameters. Think the whole ENV overwrite should more be an optin feature as this kind of magic is hard to know what the whole `?serverVersion` or even the database name get lost because it tries to inspect and overwrite given configuration file of a Symfony project.

**Comment by tucksaun** [comment]
@alexander-schranz @fbourigault did you have the opportunity to give it a go?
