### ISSUE TITLE
Not Fedora version of Symfony CLI

### ISSUE THREAD

**Issue by elxphaz** [symfony-cli/symfony-cli#109]
I've tried to install Symfony CLI on Fedora 35 I have not found how to do it on the official documentation :)
I find the yum process for installation but with last version of fedora peoples use DNF for package install anymore

**Comment by kinekt4** [comment]
Hi @sophoniie 

Follow the instructions on this page: https://symfony.com/download

Under "YUM Linux" simply replace the following line:

    sudo yum install symfony-cli

with

    sudo dnf install symfony-cli

**Comment by sophoniie** [comment]
> Hi @sophoniie
> 
> Follow the instructions on this page: https://symfony.com/download
> 
> Under "YUM Linux" simply replace the following line:
> 
> ```
> sudo yum install symfony-cli
> ```
> 
> with
> 
> ```
> sudo dnf install symfony-cli
> ```

it works thank you  😊  🎉

**Comment by fabpot** [comment]
I've just updated the https://symfony.com/download page to make it more explicit.

**Comment by elxphaz** [comment]
Great thanks @fabpot  😊
