### ISSUE TITLE
Issue with the repository for deb binaries

### ISSUE THREAD

**Issue by quatrecouleurs** [symfony-cli/symfony-cli#114]
Hello all,
Following the [official documentation](https://symfony.com/download), I tried to add the Symfony repo. However, trying to fetch at [repo.symfony.com](repo.symfony.com) gives me an Error "Certificate verification failed". Following the link I see this address : [https://repo.fury.io/symfony/](https://repo.fury.io/symfony/). 
Sorry for raising the issue here as it is probably not related to the cli code. 
I'll try the link as new repo, or to not check the certificates on the one in the doc.

**Comment by fabpot** [comment]
Probably a temporary glitch, as the instructions work for me.

**Comment by Kocal** [comment]
Yesterday one of my colleague faced the same issue and we were able to fix it by running `sudo apt install ca-certificates`. 

Looks like its CA certificates were not up-to-date.

**Comment by fabpot** [comment]
closing then.
