### ISSUE TITLE
scoop gives syntax error after installing update successfully on Windows 10

### ISSUE THREAD

**Issue by mark2016** [symfony-cli/symfony-cli#116]
Just upgraded from symfony CLI 5.4.1 to 5.4.2, got a syntax error from the scoop installer as follows:

![image](https://user-images.githubusercontent.com/16224288/159207792-ebe76d7f-a917-443a-8b6d-33b94c6286b7.png)

The symfony CLI upgrade appears to be successful, but the "shim" appears to have failed.  What is the shim for??

**Comment by mark2016** [comment]
I ran `scoop uninstall symfony-cli` and then `scoop install symfony-cli` and the shim appears to have been created successfully now: 

![image](https://user-images.githubusercontent.com/16224288/159208202-1e024475-697d-46b4-944f-4f95bc9112fa.png)

**Comment by fabpot** [comment]
Closing then.
