### ISSUE TITLE
A problem with "firewall incoming requests" in macOS

### ISSUE THREAD

**Issue by javiereguiluz** [symfony-cli/symfony-cli#117]
In the previous closed-source version of Symfony CLI, the first time I run it, I saw this dialog to allow/deny incoming requests in the macOS firewall:

![firewall-popup](https://user-images.githubusercontent.com/73419/159443916-08a87b66-3212-4889-b958-1e808ac6f9ad.jpeg)

After allowing it, I added the binary to the list of applications which are allowed incoming requests and that's it. I never saw that firewall dialog again.

-----

With the new open source version, I see the same firewall dialog whenever I run `symfony proxy:start` and `symfony serve -d`. I've tried adding the Symfony CLI binary to the list of allowed apps (both the real binary at e.g. `/opt/homebrew/Cellar/symfony-cli/5.4.2/bin/symfony` and the link to the binary at e.g. `/opt/homebrew/bin/symfony`) and I update this whenever I upgrade the Symfony CLI version, but it doesn't work.

Today I was really tired of this issue and I looked for other solutions. I found this explanation for the problem --> https://superuser.com/a/912663 and this solution for it --> https://superuser.com/a/1438094

Running the following command solved the problem for me:

```
sudo codesign --force --deep --sign - /opt/homebrew/Cellar/symfony-cli/5.4.2/bin/symfony
```

Just sharing this here in case others have the same problem or in case we can do something in this project to improve the situation. Thanks!

**Comment by Kocal** [comment]
Thanks @javiereguiluz, some of my team members and me faced the same issue!

**Comment by gndk** [comment]
Same problem here on macOs 12.2.1 and Symfony CLI 5.4.2. I think this might be a macOs Problem, not Symfony CLI, because I have the same problem when running Node stuff, for example on every `encore dev`.

Your fix worked for me, too. Thanks! At least for Symfony CLI. Can't get it to work on Node for now.

**Comment by fabpot** [comment]
@javiereguiluz Is it something we can add to the Symfony docs somewhere (and also maybe on the download page)?

**Comment by tucksaun** [comment]
maybe the Homebrew Formula can be tweaked to do it automatically on install?

**Comment by javiereguiluz** [comment]
Closing as fixed in the docs: https://github.com/symfony/symfony-docs/pull/17881

**Comment by tucksaun** [comment]
Thank you @javiereguiluz for documenting this
