### ISSUE TITLE
v5.4.3 not available in APT repository?

### ISSUE THREAD

**Issue by jmsche** [symfony-cli/symfony-cli#118]
Hi, since this morning I get an "INFO" warning telling me v5.4.3 is available.

Okay, so I update the APT repositories, but when I run "apt-get upgrade" no update for symfony-cli is available.

Is there an issue on my machine, or is v5.4.3 not available in APT repository?

**Comment by fabpot** [comment]
I think you're right @tucksaun A PR would be great indeed.

**Comment by tucksaun** [comment]
@fabpot see #119
