### ISSUE TITLE
Chocolatey package for Windows install

### ISSUE THREAD

**Issue by lpokoradi** [symfony-cli/symfony-cli#120]
Hi All,
I am thinking about to create a chocolatey (https://chocolatey.org/) package for the Symfony CLI. I just want to see if there is any interest and if we can somehow make it part of the main release process.

Any feedback is welcome!

**Comment by fabpot** [comment]
We are relying on Goreleaser for the packages. We already have support for Scoop on Windows, but unfortunately, Goreleaser does not support Chocolatey yet. See https://github.com/goreleaser/goreleaser/issues/131

Closing as we will only support it when Goreleaser supports it.

**Comment by lpokoradi** [comment]
It looks like goreleaser is not going to support chocolatey soon, what is the opinion about a manually maintained chocolatey package of symfony-cli until it supported?

**Comment by fabpot** [comment]
If you want to maintain such a package, sure, but I won't do it as I'm not a Windows user, so I would have no way to test it.
