### ISSUE TITLE
Wrong PHP version used in composer scripts

### ISSUE THREAD

**Issue by delyriand** [symfony-cli/symfony-cli#124]
I reopen the PR symfony/cli#456 :

Calling a composer script with `symfony composer <script>` uses the wrong PHP version.

Versions:
- Symfony CLI version 5.4.5
- Composer version 2.3.4

**How to reproduce?**

1. Define a different PHP version as the default one in your `.php-version` file (e.g. default: 7.4, defined: 8.0).
```
$ symfony local:php:list
+---------+----------------------------------+---------+------------------------------------+-----------------------------------+---------+---------+
| Version |            Directory             |   PHP   |                PHP                 |                PHP                | Server  | System? |
|         |                                  |   CLI   |                FPM                 |                CGI                |         |         |
+---------+----------------------------------+---------+------------------------------------+-----------------------------------+---------+---------+
| 7.3.29  | /usr                             | bin/php | sbin/php-fpm                       |                                   | PHP FPM |         |
| 7.4.28  | /usr/local                       | bin/php | Cellar/php@7.4/7.4.28/sbin/php-fpm | Cellar/php@7.4/7.4.28/bin/php-cgi | PHP FPM | *       |
| 8.0.17  | /usr/local/Cellar/php@8.0/8.0.17 | bin/php | sbin/php-fpm                       | bin/php-cgi                       | PHP FPM |         |
| 8.1.4   | /usr/local/Cellar/php/8.1.4      | bin/php | sbin/php-fpm                       | bin/php-cgi                       | PHP FPM |         |
+---------+----------------------------------+---------+------------------------------------+-----------------------------------+---------+---------+

$ cat  .php-version
8.0
```
2. Add a composer script that shows the used PHP version:
```yaml
  "scripts": {
    "test": [
      "php -v"
    ]
  },
  …
```
3. Run `symfony php -v` to ensure the right PHP version is output (here: 8.0).
4. Run `symfony composer test` - the default version will be used (here: 7.4).

If I add the verbose option on the last command (`-vvv`), I saw:
> Running 2.3.4 (2022-04-07 21:16:35) with PHP 8.0.17 on Darwin / 20.6.0

**Comment by tucksaun** [comment]
If I remember correctly, this is not supported for now because initially @fabpot and I though this kind of use case would be handled by some code like in `Symfony\Component\Process\ PhpExecutableFinder` which would correctly use the current php binary.
Here, because it execs, the system will do a new resolution of the PATH, which will opt-out what the CLI does.
One possible solution to support this would be to adjust the PATH to prepend the path where we found the PHP binary. wdyt @fabpot ?

**Comment by fabpot** [comment]
IIRC correctly, we have many strategies like setting some env vars for Composer and other tools.
Prepending the right path to PATH sounds like a good idea indeed, and that would maybe allow us to remove some other strategies that shouldn't be needed anymore.

**Comment by delyriand** [comment]
thanks @tucksaun and @fabpot!
