### ISSUE TITLE
Only install platform.sh tools when it's actually needed

### ISSUE THREAD

**Issue by ruudk** [symfony-cli/symfony-cli#13]
The cli will download the platform.sh PHAR when it's started for the first time:
```
Download additional CLI
```

I don't need platform.sh and probably never will. It would be great if this download only triggers the first time you actually need to run some cloud commands.

That way, people that only use the cli for local development, never have to download it (and waste energy doing that).

Now I get the reason why the PHAR is downloaded on first time. It's because the Platform.sh CLI is started to retrieve the commands it has, and then those commands are appended as cloud:* commands to the symfony cli. But that could also be solved by doing something like `Use 'symfony help cloud' to view all cloud commands` that would then trigger the download to retrieve the additional commands.

I could also live with a pragmatic solution: add an option to `~/.symfony5/config.json` that can be used to disable the cloud completely. That way, we can automate our development environment to always set it.

**Comment by ruudk** [comment]
Thanks for the nice fix :) Could you please tag this? Then we can start using this for all our developers (and gather more feedback 😉)

**Comment by fabpot** [comment]
Released
