### ISSUE TITLE
Wish: allow symfony CLI to use current non-empty folder

### ISSUE THREAD

**Issue by andrei-dascalu** [symfony-cli/symfony-cli#148]
Use case: I have a project folder setup to use Docker container(s) instead of local development environment. From within a container (with Symfony CLI installed) I would like to bootstrap my project in the current directory which may have some preexisting files (dockerfile, docker-compose, etc). 
It would be nice for symfony CLI to have a flag like "-f" to force using current folder even if it's not empty (maybe as long as there are no preexisting telltale things like vendor folder, symfony config, etc)

**Comment by tucksaun** [comment]
Just checked and my memories are correct: we use `composer create project`, see https://github.com/symfony-cli/symfony-cli/blob/be38fcc236252bed7362c47d9fa1ff5b5b03257c/commands/local_new.go#L329-L361
Which means were are limited to Composer ability to create a new project in an existing directory, which is not supported at the moment (see https://github.com/composer/composer/issues/1135)

**Comment by andrei-dascalu** [comment]
@tucksaun @fabpot well, the workaround I'm using is a custom script that creates the project in a temporary folder and then move the contents into the current folder once it's done. I wonder if symfony CLI couldn't do that ?
