### ISSUE TITLE
Podman(-compose) support

### ISSUE THREAD

**Issue by ArnaudLier** [symfony-cli/symfony-cli#153]
Podman is defined from [its website](https://podman.io/) as:
> a daemonless container engine for developing, managing, and running OCI Containers on your Linux System. Containers can either be run as root or in rootless mode.
Simply put: alias docker=podman

It's a great alternative to Docker and it has a script named [podman-compose](https://github.com/containers/podman-compose)
It would be great to see the same features available with Docker directly implemented in the CLI.

- [ ] Uses of `docker-compose` in the book-related commands
- [ ] Environment variables inferring
- [ ] ...

**Comment by fabpot** [comment]
Closing as there is no traction here.
If someone wants to add support for Podman, I will be happy to review a pull request.
