### ISSUE TITLE
--webapp does not work

### ISSUE THREAD

**Issue by sblondeau** [symfony-cli/symfony-cli#157]
Hello,
Since few days, it seems that option --webapp in `symfony new my_project --webapp` does not work anymore
Project is created but additional "web" component and webpack encore configuration are not loaded 

I am on last version of Symfony CLI  5.4.12 

Thanks for you help

**Comment by tucksaun** [comment]
Hi @sblondeau 

This is due to the fact the `webapp-pack` does not require`symfony/webpack-encore-bundle` anymore.
You can refer to https://github.com/symfony/webapp-pack/pull/7 for more information.
