### ISSUE TITLE
New command to change tld for symfony proxy

### ISSUE THREAD

**Issue by MrYamous** [symfony-cli/symfony-cli#159]
Hi,

When we use Symfony local proxy, default tld is ".wip"
[Documentation](https://symfony.com/doc/current/setup/symfony_server.html#defining-the-local-domain) explain how to change it manually, but what would you think about adding a command to do it ? 

It's not a major improvement but I guess it can still be helpful and maybe more convenient to use

**Comment by Nihilus118** [comment]
Hi @tucksaun,

please take a look at the branch I just created. I've implemented a new command to change the top-level domain (TLD) of the local proxy. Additionally, I've made modifications to the existing command `local:proxy:domain:attach` to support an argument for specifying a TLD when attaching domains.

I'm uncertain whether this approach is the most optimal or if it aligns with your considerations for backward compatibility.

**Comment by tucksaun** [comment]
@Nihilus118 thank you for working on this.

a PR would be easier for @fabpot and I to review the code (and to comment).

**Comment by Nihilus118** [comment]
Hi @tucksaun, I created a PR as requested. The pipeline also passed successfully.
