### ISSUE TITLE
Mac install says to update already-updated Mac

### ISSUE THREAD

**Issue by givihuda** [symfony-cli/symfony-cli#160]
I'm following the instructions in the macOS tab to install Symfony CLI using Homebrew:
https://symfony.com/download

`brew install symfony-cli/tap/symfony-cli`

EDIT: Sorry, I accidentally submitted too soon; updating...

However, this is giving me a strange error:

```
==> Installing symfony-cli from symfony-cli/tap
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install
```

So, my macOS is already updated to the latest Monterey; I know because I just updated it yesterday, and there's no new updates in the Apple button > System Preferences > Software Updates.

So now I'm afraid to just run the suggested command line when it appears it's going to try to update macOS some way (which could have unpredictable consequences) when I've already done it through the Mac's pop-up suggestions...

So now I'm wondering, is the error just trying to tell me that I need to update my XCode? If so, why is it suggesting I completely recursively permanently delete my CommandLineTools directory then reinstall from a suggested command? This is making me really concerned. Apple changes _a lot of things_ each major update since Catalina, so maybe those commands won't do what this repo's maintainers think they will on Monterey...

I think XCode was required to install git the recommended way... I'm not sure. XCode and git may have been pre-installed since I received the computer set up (at least partially) from my employer. Deleting the CommandLineTools directory seems like it would break a lot of things.

So... is it the best idea to recommend these commands for this issue ("Your Command Line Tools are too outdated.")? Or are there better recommendations based on macOS version?

I suppose I can check what version my XCode is at and how to update it the Apple-recommended way, but I'm scratching my head on Symfony CLI's output at the moment.

**Comment by tucksaun** [comment]
Hi,

This output is not coming from symfony-cli nor its brew recipes but is the direct output of Homebrew (see https://github.com/Homebrew/brew/blob/2258ba5797c1ea8149a49673b5c080011c366237/Library/Homebrew/os/mac/xcode.rb#L320-L339) so there's nothing Symfony CLI's maintainers can do about it.

You should probably get back to Homebrew's team about your concerns regarding those commands or if you think there are more appropriate ones that can be used.

In the meantime you can try to open Xcode, maybe it will suggests you some updates if there is some available.
Or, you can direct download the binaries from the [releases](https://github.com/symfony-cli/symfony-cli/releases) section and proceed with a manual installation.

**Comment by givihuda** [comment]
I'm not seeing which release to download for Mac in your 'releases' link. The links mention Windows and Linux but not Mac.

**Comment by tucksaun** [comment]
Another name sometimes used to refer to macOS is "Darwin" so you can use the "symfony-cli_darwin_all.tar.gz" file

**Comment by givihuda** [comment]
With an explanation for why Mac OS is referred to as "Darwin" being a dozen+ paragraphs long - https://apple.stackexchange.com/a/401881/417970 - maybe Symfony maintainers should stop referring to it as "Darwin" and start simply referring to the Mac download files with "Mac", like they simply refer to the Windows files with "Windows" and the Linux files with "Linux".

Maybe there's a paragraphs-long explanation for why that hasn't happened yet, I don't know, but if there is, that's another reason to make it simple and consistent.

**Comment by tucksaun** [comment]
This is a quite common practice: one of the most simplest explanation is that the system qualifies itself as "Darwin".
You can see that yourself when running `uname` or having a look at the `PHP_OS` constant.
So using "darwin" is quite handy when writing automation and that's why the tool used for releasing is using "darwin" (the same way it uses "Linux" instead of a more complete and more appropriate name).

**Comment by givihuda** [comment]
Fair enough. I suppose I haven't needed to look at those constants in my development on Mac.
