### ISSUE TITLE
[FEAT] add `--bundle` option for `symfony new` command

### ISSUE THREAD

**Issue by Lenny4** [symfony-cli/symfony-cli#163]
```
Symfony CLI version 5.4.12
```

When I type `symfony new --help` I got these options:

```
Options:
  --dir=value      Project directory
  --version=value  The version of the Symfony skeleton (a version or one of "lts", "stable", "next", or "previous")
  --full           Use github.com/symfony/website-skeleton (deprecated, use --webapp instead)
  --demo           Use github.com/symfony/demo
  --webapp         Add the webapp pack to get a fully configured web project
  --book           Clone the Symfony: The Fast Track book project
  --docker         Enable Docker support
  --no-git         Do not initialize Git
  --cloud          Initialize Platform.sh
  --debug          Display commands output
  --php=value      PHP version to use
```

Is it possible to add another option:
```
  --bundle           Create a reusable Bundles
```
Once launched it would be nice to have a list a questions:
1) Author username ?
2) Vendor name ?
3) Vendor namespace ?
...

This way the package will be intialized with all the [Best Practices](https://symfony.com/doc/current/bundles/best_practices.html)

Something similar to https://github.com/spatie/package-skeleton-php

**Comment by tucksaun** [comment]
I'm not sure this falls into the scope of the CLI that is really project's oriented.
Also the CLI doesn't really have a way to manipulate PHP files at the moment so this would require some extra work.

I have the feeling that Maker Bundle would be a better candidate for this feature: it probably has most of the infrastructure required for this feature.

**Comment by tucksaun** [comment]
[SensioGeneratorBundle](https://github.com/sensiolabs/SensioGeneratorBundle) used to do it after all (but creating bundle was required for every Symfony projects back then which is not the case anymore)
