### ISSUE TITLE
Support for cloudlinux 8.6

### ISSUE THREAD

**Issue by LukanoX** [symfony-cli/symfony-cli#173]
Hi, will you add support for cloudlinux 8.6?

curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.rpm.sh' | distro=cloudlinux  version=8.6  codename=Leonid  arch=x86_64 sudo -E bash
Executing the  setup script for the 'symfony/stable' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'rpm' ...
   OK: Importing 'symfony/stable' repository GPG keys into rpm ...
   OK: Checking for available package manager (DNF/Microdnf/YUM/Zypper) ...
 ^^^^: ... Detected package manager as 'dnf'
   OK: Checking for dnf dependency 'yum-utils' ...
 NOPE: Checking for dnf dependency 'dnf-plugin-config-manager' ...
   OK: Attempting to install 'dnf-plugin-config-manager' ...
 NOPE: Checking if upstream install config is OK ...
 ^^^^: ... Failed to fetch configuration for your OS distribution release/version.
 >>>>:
 >>>>: It looks like we don't currently support your distribution release and
 >>>>: version. This is something that we can fix by adding it to our list of
 >>>>: supported versions (see contact us below), or you can manually override
 >>>>: the values below to an equivalent distribution that we do support:
 >>>>:
 >>>>: ... distro=cloudlinux  version=8.6  codename=Leonid  arch=x86_64
 >>>>:
 >>>>: You can force this script to use a particular value by specifying distro,
 >>>>: version, or codename via environment variable. E.g., to specify a distro
 >>>>: such as SUSE Linux Enterprise Server 12, use the following:
 >>>>:
 >>>>:   <curl command> | distro=sles version=12.1 codename= sudo -E bash
 >>>>:
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!:
 !!!!: You can contact Symfony for further assistance.
 !!!!:
 !!!!: URL: https://github.com/symfony-cli/symfony-cli

**Comment by fabpot** [comment]
I think you need to contact Cloudsmith.
