### ISSUE TITLE
symfonycorp/cli docker image not found (404) on DockerHub

### ISSUE THREAD

**Issue by pbories** [symfony-cli/symfony-cli#177]
Hello,

As mentionned in Symfony support channel on Slack, some CI workflows fail on Github when using symfonycorp/security-checker-action. 

Here is the error message :
![image](https://user-images.githubusercontent.com/40885411/187911932-23f3dcaf-5761-4397-b034-7478281f2338.png)

We found out that this URL was sending a 404 response :
https://hub.docker.com/r/symfonycorp/cli

Does anyone have any information about this docker image ? Why did it disappear ? 

To get rid of this error, we now have to download and install Symfony CLI and then run `symfony security:check` in our CI workflow.

Is there any alternative ?

Thank you all !

**Comment by fabpot** [comment]
Hi, sorry for the inconvenience. I've removed the image as this is still using the non-Open-Source version of the Symfony CLI, which is not maintained anymore. I did not think about symfonycorp/security-checker-action, but this should also be deprecated now.

**Comment by fabpot** [comment]
You should probably upgrade to the latest version of https://github.com/fabpot/local-php-security-checker which does not rely on it anymore.
See https://github.com/symfonycorp/security-checker-action/commit/2e021d6b2dbcc90565d817112175b2bdcf07acaa

**Comment by pbories** [comment]
Thank you for your lighning fast answer, @fabpot.

**Comment by bbashy** [comment]
Thanks for that info too. Was using v2 of symfonycorp/security-checker-action.

**Comment by lecajer** [comment]
Here is an alternative of the handy docker image :
- Download the latest corresponding binary from https://github.com/symfony-cli/symfony-cli/releases/
- Extract the tar.gz file
- Run `./symfony security:check`

Example :
```yml
      - run: |
          wget https://github.com/symfony-cli/symfony-cli/releases/download/v5.4.13/symfony-cli_linux_amd64.tar.gz
          tar -xzf symfony-cli_linux_amd64.tar.gz
          ./symfony security:check
```

**Comment by lecajer** [comment]
To check vulnerabilities it might be easier to use a new feature of composer :
https://php.watch/articles/composer-audit

(Thanks [ggacoin](https://github.com/ggacoin))
