### ISSUE TITLE
Docker images for symfonycorp/cli

### ISSUE THREAD

**Issue by themao** [symfony-cli/symfony-cli#179]
Hi guys, started my morning with failing builds which tried to pull the Docker image for symfony-cli and did not find anything at https://hub.docker.com/r/symfonycorp/cli, it gives 404 now. Did someone accidentally delete something?

**Comment by fabpot** [comment]
This has been removed as it was for the non Open-source and not maintained old Symfony CLI. You need to upgrade to the one in this repo.
