### ISSUE TITLE
Unable to locate package symfony-cli

### ISSUE THREAD

**Issue by bneumann97** [symfony-cli/symfony-cli#180]
I'm trying to install the symfony-cli on a Raspberry Pi 3 running Raspbian. 

I ran the script:
`curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | sudo -E bash`

`sudp apt update` shows me 

`Get:5 https://dl.cloudsmith.io/public/symfony/stable/deb/raspbian bullseye InRelease [5,077 B]`

After that, I ran:

```
sudo apt install symfony-cli

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package symfony-cli
```

I also tried to change the source to `https://dl.cloudsmith.io/public/symfony/stable/deb/debian bullseye InRelease` without success

**Comment by tucksaun** [comment]
(Reopened because the PR fixing this has been reverted)
