### ISSUE TITLE
Symfony CLI doesn't find all the php versions on my system

### ISSUE THREAD

**Issue by eved42** [symfony-cli/symfony-cli#182]
I created a Symfony 6 project locally on my PC (Windows 11 Entreprise v.21H2) and I want to use a specific version of PHP. I know that we can use different versions by creating a `.php-version` file in the project root.

So I did this command `symfony local:php:list` to see the choices I have and it only shows Wamp64 and Xampp php that I don't want to use. I have many other versions inside `C:/php/` folder and I would like to select one of them.

Why Symfony CLI doesn't show them in the list ? And how to fix that ?

For info, I work with a non-admin user account on my PC but I have another admin account for installing programs.

![php versions](https://user-images.githubusercontent.com/12841417/189357306-45af40e7-7c32-48d0-be44-b8ff02a67043.png)
![2022-09-08 10_28_07-php](https://user-images.githubusercontent.com/12841417/189357340-0abb0398-c9b4-4b97-8a2b-e684b4d7b576.png)

**Comment by tucksaun** [comment]
Hello @eved42

The Symfony CLI only recognizes PHP installations available in the PATH and in directories for some well-known package managers (as Chocolatey) or tools (as Wamp).

As of now, if you want a quick way to make the CLI find your versions you can either move your subdirectories from `c:\php` to `c:\wamp64\bin\php` or you can add each one of them to your PATH

**Comment by eved42** [comment]
Ok thank you for your answer @tucksaun
