### ISSUE TITLE
RFE: generator improvement for default crud

### ISSUE THREAD

**Issue by omgslinux** [symfony-cli/symfony-cli#183]
Every time controller class is created by make:, though it works, I need to customize more things than expected, when there could be a single "point of failure". For this, I create a local constant name PREFIX containing the common prefix for naming. So, if I create an example controller named "Company", and do the mentioned work, the diff (using annotations, but it's not very different with attributes) is like this:

```
14c14                                     
<  * @Route("/company", name="app_company_")                                                                                                                             
---                                       
>  * @Route("/company")                                                                                                                                                  
18d17
<     const PREFIX = 'app_company_';
20c19
<      * @Route("/", name="index", methods={"GET"})
---
>      * @Route("/", name="app_company_index", methods={"GET"})
30c29
<      * @Route("/new", name="new", methods={"GET", "POST"})
---
>      * @Route("/new", name="app_company_new", methods={"GET", "POST"})
41c40
<             return $this->redirectToRoute(self::PREFIX . 'index', [], Response::HTTP_SEE_OTHER);
---
>             return $this->redirectToRoute('app_company_index', [], Response::HTTP_SEE_OTHER);
51c50
<      * @Route("/{id}", name="show", methods={"GET"})
---
>      * @Route("/{id}", name="app_company_show", methods={"GET"})
61c60
<      * @Route("/{id}/edit", name="edit", methods={"GET", "POST"})
---
>      * @Route("/{id}/edit", name="app_company_edit", methods={"GET", "POST"})
71c70
<             return $this->redirectToRoute(self::PREFIX . 'index', [], Response::HTTP_SEE_OTHER);
---
>             return $this->redirectToRoute('app_company_index', [], Response::HTTP_SEE_OTHER);
81c80
<      * @Route("/{id}", name="delete", methods={"POST"})
---
>      * @Route("/{id}", name="app_company_delete", methods={"POST"})
89c88
<         return $this->redirectToRoute(self::PREFIX . 'index', [], Response::HTTP_SEE_OTHER);
---
>         return $this->redirectToRoute('app_company_index', [], Response::HTTP_SEE_OTHER);

```

Then, going a bit further, I usually extend this to the templates, by passing an extra PREFIX variable with <code>self::PREFIX</code> as value to every template that has a link to 'app_X_y' in any path (replacing every ocurrence of <code>path('app_X_y')</code> with <code>path(PREFIX ~ 'y')</code>).

This way, there's a single "point of failure", where just setting at the start of the controller class the same value for the constant than the defined name in the router, nothing else has to be changed along the crud files, what is a headache and a lot of work. So, if you find this useful, I'd ask to change the skeleton of the make: generator to produce this result.

Thanks in advance.

**Comment by tucksaun** [comment]
hi @omgslinux

this make command you are referring to is part of [symfony/maker-bundle](https://github.com/symfony/maker-bundle) so you'll need to bring your suggestion there :)
