### ISSUE TITLE
Installer generate wrong download url

### ISSUE THREAD

**Issue by jeje-ch** [symfony-cli/symfony-cli#194]
The installer generates `https://github.com/symfony-cli/symfony-cli/releases/latest/download/symfony-cli_linux_arm64.tar.gz` which return a 404; using `https://github.com/symfony-cli/symfony-cli/releases/download/v5.4.15/symfony-cli_5.4.15_linux_arm64.tar.gz` works fine.

**Comment by tucksaun** [comment]
It's not that the installer generated a wrong URL, it's more the other way around: the archives named changed in 64487345cb4808fb525d151d7cd2ec51d1112a14.

@fabpot is it possible to revert 64487345cb4808fb525d151d7cd2ec51d1112a14?
currently the installer has not way of determining the version to build the filename :/

**Comment by jakubtobiasz** [comment]
Hi 🙋🏼‍♂️!

Totally agree. PHP Setup action by @shivammathur is dead, also `https://get.symfony.com/cli/installer` fails in my docker images 💀.

**Comment by mtovmassian** [comment]
Experiencing the same issue in our CI pipeline. Is there a quick temporary workaround to deliver anyway?

**Comment by jakubtobiasz** [comment]
@mtovmassian 

If you use Setup PHP action:
Look at our temporary solution in Sylius' builds -> https://github.com/Sylius/Sylius/pull/14425

If you use Docker:
Replace the installer with the solution from above.

**Comment by oallain** [comment]
Hello,

IMO, this issue is fixed with [v5.4.16](https://github.com/symfony-cli/symfony-cli/releases/tag/v5.4.16).

Regards.

**Comment by jakubtobiasz** [comment]
Yes, it works. Thanks, @fabpot for the fast fix 🎉!

**Comment by fabpot** [comment]
Fixed now with 5.4.16.
