### ISSUE TITLE
Installer always install latest version

### ISSUE THREAD

**Issue by jeje-ch** [symfony-cli/symfony-cli#195]
It could be nice to let the ability to the user to choose which version of symfony-cli he install.

I mean, `wget https://get.symfony.com/cli/installer -O - | bash` will install by default the latest version (as it is now in fact) and `wget https://get.symfony.com/cli/installer --version=x.y.z -O - | bash` will let the user choose the version he want.

**Comment by fabpot** [comment]
What would be the use case?
If you know which version you want, why not download the binary directly then?

**Comment by jeje-ch** [comment]
Hello Fabien,

Thank you first for all your job, and more to taking time on a Sunday :-)

If you decide to no more support a given architecture for example, or to fix the version to an older one the time an other issue is fixed.

On my side, the install is done in a Dockerfile part of a project which is shared by different developer having different kind of architecture, and I can't then put a fixed binary.

BTW: I was thinking to push a PR in a few days about it, but will not do it if you don't find any value in it

Thank you again

**Comment by fabpot** [comment]
Let's see what a PR would look like ;)

**Comment by tucksaun** [comment]
I would instead recommend to not rely on an external installer in a Dockerfile but rather determine the architecture dynamically (using `uname -m` fort example)

**Comment by jeje-ch** [comment]
@tucksaun it's basically what does the symfony installer, no ? I understand and agree your point of view about an external installer in a Dockerfile, but in my case I talk about a Dockerfile used in a dev environment

**Comment by tucksaun** [comment]
To be clear: I don't think this option should not exist but for a Docker context I think it is better to provide a good Docker snippet that does not rely on the installer on symfony.com/download or, more idiomatic, directly provide a Docker image that one can use as-is or COPY from it.

**Comment by tucksaun** [comment]
@jeje-ch the CLI is now also released as a Docker image, so if you want you should be able to do something like this if this works for you:

```
COPY --from=ghcr.io/symfony-cli/symfony-cli:5.4.18 /usr/local/bin/symfony /usr/local/bin/symfony
```

But if you prefer to run the installer with a `--version` flag that can work as well :)

**Comment by tucksaun** [comment]
@florianfish please have a look at the new flags introduced in https://github.com/symfony-cli/symfony-cli/pull/525
if this does not solve your issue please open a new issue with more details about what does not work
