### ISSUE TITLE
Symfony Demo - Sqlite is readonly - missing mount in .platform.app.yaml

### ISSUE THREAD

**Issue by flovntp** [symfony-cli/symfony-cli#202]
Hi, 
I'm preparing the SFCon 2022 workshop and i was trying to use the demo project and push it to Platform.sh, using symfony cli.
basically : 

```
symfony new --demo --cloud /path/to/demo
cd /path/to/demo
symfony project:create --title=demo --plan=development
symfony deploy
```
So, my issue is that Sqlite is not writable
```
SQLSTATE[HY000]: General error: 8 attempt to write a readonly database 
``` 
Solution : there is missing mount point on `/data` into the generated `.platform.app.yaml` file, for Sqlite to be writable. 
```
mounts:
    "/var": { source: local, source_path: var }
    "/data": { source: local, source_path: data }
```

Hope it helps.

Note: you gave me a WoW effect, so easy to use Symfony with Platform.sh ;)

**Comment by fabpot** [comment]
Fixed now

**Comment by flovntp** [comment]
Hi @tucksaun @fabpot 
seems that there is an issue with the generated .platform.app.yaml file (indentation issue) 
```
mounts:
    "/var": { source: local, source_path: var }
    "/data": { source: local, source_path: "data" }hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | bash
        
        symfony-build
```
`hooks` should be on a new line and not at the end of the data mount declaration.

Could you please reopen this issue ?

**Comment by fabpot** [comment]
It worked for me. Can you tell us what you did to have this issue?

**Comment by tucksaun** [comment]
(see https://github.com/symfonycorp/cloud-templates/pull/29)
