### ISSUE TITLE
Product XP - be able to create a new project while using symfony:deploy

### ISSUE THREAD

**Issue by flovntp** [symfony-cli/symfony-cli#207]
Hi, 

To ease user experience, could it be possible to add an option while using `symfony deploy` and if no PSH project is linked to current sources, to be able to create a new project on PSH side (like if using `symfony cloud:create` ? 
At this time, it's only displaying the list of existing PSH projects but no option to create a new one.
my 2 cents ;)

**Comment by fabpot** [comment]
I agree with you and that was the PX previously, but we are now using the plain psh binary behind the scene. So, this is where you should suggest this change ;)
