### ISSUE TITLE
`symfony build` does not exist

### ISSUE THREAD

**Issue by flovntp** [symfony-cli/symfony-cli#208]
Hi, 

After trying to get a PSH project (workshop for SFCon), i try to run suggested command from `symfony get xxxxx` execution :

```
flovntp@VNTP-Book-2 PlatformSH % symfony get 4qqp5j5vtvnom
...
The project SFCon - Bigfoot1 - workshop (4qqp5j5vtvnom) was successfully downloaded to: sfcon-bigfoot1-workshop

You can build the project with: 
    cd sfcon-bigfoot1-workshop
    symfony build
flovntp@VNTP-Book-2 PlatformSH % cd sfcon-bigfoot1-workshop && symfony build
  Command "build" does not exist.  
flovntp@VNTP-Book-2 sfcon-bigfoot1-workshop % symfony list | grep build 
  cloud:project:clear-build-cache                                                     Clear a project's build cache
flovntp@VNTP-Book-2 sfcon-bigfoot1-workshop % platform list | grep build 
  local:build (build)                                           Build the current project locally
  project:clear-build-cache                                     Clear a project's build cache
```

It seems that suggestion is not the good one, `platform local:build` exists but not `symfony build`. 
what is the symfony cli equivalent for `local:build`?

**Comment by fabpot** [comment]
Indeed, there is no such thing as `symfony build`.

**Comment by flovntp** [comment]
@fabpot so maybe, it could be great to change the suggestion at the end of the `symfony get xxx` 😄

**Comment by fabpot** [comment]
Don't use `get`. It just does not and cannot work. Frankly, I've never understood this command :)

**Comment by flovntp** [comment]
ok, 
then, how to get an existing PSH project locally? 
i try to find it in the sf doc but it's only showing how to work on a local project already deploy on PSH https://symfony.com/doc/current/cloud/getting-started.html#working-on-a-project
