### ISSUE TITLE
[^5.4.17][Windows] TLS handshake error 

### ISSUE THREAD

**Issue by Guilain** [symfony-cli/symfony-cli#227]
Hello,

Since 5.4.17+, i get this error on Windows 11.
```
http: TLS handshake error from 127.0.0.1:55733: read tcp 127.0.0.1:8000->127.0.0.1:55733: wsarecv: An existing connection was forcibly closed by the remote host.
```
I use local domain names and proxy.pac is well configured.

If i rollback to 5.4.16, everything is working well.

**Comment by tucksaun** [comment]
Hey there,

Could you let me know when and where this happens?

Thanks

**Comment by Guilain** [comment]
Hey,

It happens everytime i try to access a local domain.
> https://127.0.0.1:8000 is working well

> https://xxxx.wip
 `http: TLS handshake error from 127.0.0.1:52510: read tcp 127.0.0.1:8000->127.0.0.1:52510: wsarecv: An existing connection was forcibly closed by the remote host.`

Reinstalling certificates and regenerating local domains didn't change anything.

I forgot, i'm using PHP 8.1 & Symfony 6.1.
PHP 8.1 & Symfony-cli are installed by Scoop.

Thanks

**Comment by tucksaun** [comment]
I should be able to have a look during the Christmas holidays as I will have a Windows computer available for debugging.

**Comment by Guilain** [comment]
Hello,
After several tests... it seems to be an AV error...
I currently use Kaspersky.
Disabling it and allowing symfony-cli in windows firewall works.

@tucksaun thanks for yours answers and your time.

I wish you happy Christmas holidays.

**Comment by tucksaun** [comment]
Thank you @Guilain for the investigation and the feedback.
