### ISSUE TITLE
JSON Schema for .symfony.local.yaml

### ISSUE THREAD

**Issue by shyim** [symfony-cli/symfony-cli#236]
I hate looking into docs to find out how the config file is structured. For this reason I would suggest creating a simple JSON schema for that file and submitting to https://www.schemastore.org/json/

So when someone creates that file, the editor autopickups the configuration and shows completion. :)

I can create the PR to add a schema and help getting into schemastore if wanted

**Comment by fabpot** [comment]
This is an undocumented feature :) And one that was never announced. So, it's sort of hidden in the code.
That's because I'm not fully satisfied with the way it works and I might change it drastically at some point.

**Comment by shyim** [comment]
It is a little bit documented here :) https://symfony.com/doc/current/setup/symfony_server.html#configuring-workers

I would like to extend the config using PR's. Like defining the php-fpm max_children and so as it is currently hard-code :)

**Comment by fabpot** [comment]
Arf, didn't see the related PR.
@javiereguiluz Can you mark this feature as experimental in the docs?

**Comment by javiereguiluz** [comment]
We can close this as fixed in https://github.com/symfony/symfony-docs/pull/17475

**Comment by tucksaun** [comment]
Thank you @javiereguiluz 

I'm closing this one for now as I don't think publishing an "official" JSON schema for an experimental feature makes sense.
Let's reassess if and when the feature is stabilized.
