### ISSUE TITLE
Proxy not happy when used with Windows mklink to %userprofile%\.symfony5 folder 

### ISSUE THREAD

**Issue by spamhater-grav** [symfony-cli/symfony-cli#242]
Hi All, I wonder if I am doing something wrong, still quite new to symfony as I am using Grav CMS , 

I have a ramdrive on my machine o speed things up and try and to stop so much file thrashing on my M2 drive,  (auto sync every 5 minutes)

Windows 10 (64)

Symfony-cli installed by choco (C:\program files\symfony.exe)
PHP install is running r:\.php
Grav is installed to R:\grav

Wanting to use the 'pretty url' proxy feature and the symfony local  server for developing,
Normally I know the data/logging for the folder installs into the %userprofile%\.symfony5 as well as the certificates 

I am trying to get everything running in a 'portable mode'  as possible. 
 I thought I would be able to make use of MKLINK command and create a directory / junction to my 4GB ramdrive for testing.

But when I run `symfony local:proxy:start` it doesn't seem happy in its response. See image attached
Is this by design or I am doing something wrong

![image](https://user-images.githubusercontent.com/84087968/207639881-f6998c19-0a99-4776-9734-11f8d4d06e65.png)

many thanks Nick

**Comment by tucksaun** [comment]
Hi there,

To make some features work properly the CLI watches files modifications and to do so efficiently it uses FS notifications.
Your error message seems related to this. Maybe your ramdrive does not support this kind of features?

Can you try without the ramdrive and see what happens?

**Comment by spamhater-grav** [comment]
Thanks tucksaun for the reply. Yep it does work happily on a local drive, so as you suggested it probably the ramdrive interfering. 

Is there any switches that can be used to redirect any temp files to a different location , I will have a play at this end and see if anything I can find at the end.

**Comment by tucksaun** [comment]
no switches to change this directory location at the moment

**Comment by spamhater-grav** [comment]
Just a small update.. I thought I had written a reply I did find one reason why it might have not worked and cause the error and it was all my fault .  I was using Imdisk ramdrive and I did enable ntfs compression option on the drive.  This was the thing that produce the original error. I haven't had further time to investigate at present, but you have gave me a direction to head to .

Prob will try with fat formatted ramdrive and retest .. 

Thanks for your help  :)
