### ISSUE TITLE
Timeout with proxy and TLS

### ISSUE THREAD

**Issue by antiseptikk** [symfony-cli/symfony-cli#25]
Hi, 

I've got `ERR_TIMED_OUT ` in proxy with .wip domain and with TLS enabled. it works without TLS.

- I'm on MacOs 11.5.2.
- I ran `ca:install` command and copy proxy.json from symfony-cli v4
- TLS working with 127.0.0.1:8000

**Comment by ruudk** [comment]
I also noticed that as of V5 HTTPS / TLS seems to be completely broken.
