### ISSUE TITLE
Tool stalled at "Download additional CLI tools..."

### ISSUE THREAD

**Issue by carlos-granados** [symfony-cli/symfony-cli#250]
Today I tried to deploy to plaformsh using the `symfony cloud:deploy` command. It asked me to update the platformsh CLI tools to version 4.0.0 and I agreed. After that I ran the command again and it stalled showing "Downloading additional CLI tools..." It's been there for several hours and I cannot get it to go forward. What can be done to fix this problem?

**Comment by lolautruche** [comment]
Hi @carlos-granados 
Can you please try to install the new version of the Platform.sh CLI as documented here: https://docs.platform.sh/administration/cli.html ?

**Comment by carlos-granados** [comment]
I already did that and the problem continues

**Comment by codingfogey** [comment]
Same issue here.

I was asked by Symfony CLI to update Platform CLI to 4.0. After Installation I was asked to delete the old 3.x Platform CLI.

I did both.

Now Symfony CLI tries and fails to download "additional CLI tools". Interrupting the Download after several minutes results in  
`Could not open input file: <path_to_home>/.platformsh/bin/platform`. 

Symfony CLI creates a file `platformsh-installer.php` in my home directory and removes it when interrupted.

Symfony CLI and Platform CLI are both installed (and reinstalled) via home-brew.

**Comment by carlos-granados** [comment]
More info:
The platform CLI seems to be working fine. I was able to deploy the code by running `platform push`. It is the connection between the Symfony CLI and the new platform CLI that seems broken

**Comment by carlos-granados** [comment]
Ah, and this all under MacOS

**Comment by walva** [comment]
I have the same problem. Also on MacOS. I install both symfony-cli and platform cli using brew.
When I run `whereis platform` it gives:
`platform: /opt/homebrew/bin/platform`

**Comment by fabpot** [comment]
Should be fixed by #253
