### ISSUE TITLE
Allow create project in current dir

### ISSUE THREAD

**Issue by Aziz403** [symfony-cli/symfony-cli#251]
I'm trying to create a project in my current command line directory: `new symfony./`
Throwing error: `project directory. / is not empty`.
I don't know if it's not possible or am I writing invalid syntax?

**Comment by henrikac** [comment]
I just tried both `symfony new .` and `symfony new ./` and I did not get any errors - both created a new project in the current directory.

```
symfony-cli  v. 5.4.20
macOS Monterey 12.6
```
