### ISSUE TITLE
Composer not found

### ISSUE THREAD

**Issue by MichaelBrauner** [symfony-cli/symfony-cli#256]
Hello everyone, 

I use the symfony-cli to create new project: 

```
symfony new --webapp my_project
```

I get the message: 

> WARNING: Unable to find Composer, downloading one. It is recommended to install Composer yourself at https://getcomposer.org/download/

My composer is installed correctly: 

```shell
which composer
/usr/local/bin/composer
```

Could this possibly be a small bug?

**Comment by henrikac** [comment]
I just tried the exact same command `symfony new --webapp test` and I did not see this warning.

This was done with `symfony-cli v5.4.20` on `macOS Ventura 13.1`.

**Comment by MichaelBrauner** [comment]
I am on linux (POP!_OS) - latest Ubuntu will maybe have the same issue I can imagine.
