### ISSUE TITLE
symfony new creates a composer.json that will fail on Platform.Sh

### ISSUE THREAD

**Issue by matthiaz** [symfony-cli/symfony-cli#258]
The documentation on how to start a new symfony project on platform.sh might need a bit of changing. 

https://symfony.com/doc/current/cloud/getting-started.html#configuring-platform-sh-for-a-project

It mentions to run `symfony new --demo --cloud symfony-test` which will automatically create a `composer.json` file. Unfortunatly that composer.json file includes a `post-install-cmd` which tries to connect with the symfony database. This is a problem on platform.sh because during the `install` step, you do not have access to the database (because it happens in the build step).

```
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
```

Possible solution:

Remove this part:
```
        "post-install-cmd": [
            "@auto-scripts"
        ],
```
And document that cache clearing needs to be done in the deploy hook.

I'm not entirely sure where this is generated though.

**Comment by Lustmored** [comment]
Well for me this just works on all projects (I'm on platform for quite some time already). I know this issue comes from the slack, where the real problem was about enabling some bundles.

Symfony build/deploy scripts are in fact pretty nice as they prepare production cache during build and then, in deploy, use those instead of calling `cache:clear` again - this saves some precious downtime (about a minute on my project) during production deploy comparing to other environments.

This being said I'm pretty sure the real problem is somewhere else (a missing dependency probably).

**Comment by luimen6** [comment]
Same problem like @matthiaz

**Comment by matthiaz** [comment]
It was indeed mentioned on slack. But that is not what I used to base this on.

To replicate this issue, simply create a new symfony project.
`symfony new --demo --cloud symfony-test` and then try to push it to a fresh platform project without data.

You mention that during build the cache is prepared. Can you share where symfony is trying to store that cache? On platform.sh, it has no access to the database nor any mount points during the build step. Build steps are reusable across environments and are only responsible for creating the actual code package.

**Comment by fabpot** [comment]
It's weird as Symfony does not connect to the DB during the build... except if the DB DSN is not configured well.
The demo is using SQLite, so should never be an issue.
I will try to try it myself soon.

**Comment by Lustmored** [comment]
@matthiaz Sure - my build looks like this:

```
build: |
      set -x -e
      
      curl -fs https://get.symfony.com/cloud/configurator | (>&2 bash)
      
      (>&2 symfony-build)
```

It uses scripts from https://get.symfony.com/cloud/stable/tools.tar.bz2

Within this we get `symfony-build`:

```
#!/bin/bash
set -xeuo pipefail

# (c) 2018-2022 Symfony SAS
# All Rights Reserved

# remove the development front-controller if present
rm -f web/index_dev.php web/app_dev.php public/index_dev.php public/app_dev.php

# install PHP extensions
exts=$(echo "$PLATFORM_VARIABLES" | base64 -d | jq -r 'with_entries(select(.key | startswith("php-ext:"))) | to_entries[] | [.key, .value] | join(":")')
for ext in $exts; do
    name=$(echo "$ext" | cut -d':' -f 2)
    version=$(echo "$ext" | cut -d':' -f 3)
    php-ext-install "$name" "$version"
done

# we always install dev deps (for dev env we need them and we can't know where our image will be deployed)
# shellcheck disable=SC2086
symfony composer install --prefer-dist ${COMPOSER_FLAGS:-} --no-scripts --no-progress --no-ansi --no-interaction
# we force a prod deployment (Flex only)
if composer show symfony/flex >/dev/null 2>/dev/null; then
    symfony composer dump-env prod || true
    # shellcheck disable=SC2086
    symfony composer install --prefer-dist --optimize-autoloader --apcu-autoloader --classmap-authoritative ${COMPOSER_FLAGS:-} --no-progress --no-ansi --no-interaction
    # move cache if generated (not the case when symfony/console is not installed -- display a warning in such a case)
    if [[ -d "${SYMFONY_APP_CACHE_DIR:-var/cache}/${APP_ENV:-prod}" ]]; then
        mkdir -p tmp/cache && mv "${SYMFONY_APP_CACHE_DIR:-var/cache}/${APP_ENV:-prod}" tmp/cache/
    else
        echo -e "Cache was not generated as symfony/console is not installed, you should require it!"
    fi
else
    # shellcheck disable=SC2086
    symfony composer install --prefer-dist --optimize-autoloader --apcu-autoloader --classmap-authoritative ${COMPOSER_FLAGS:-} --no-progress --no-ansi --no-interaction
fi

node-build
```

The line that caches configuration is:
```
mkdir -p tmp/cache && mv "${SYMFONY_APP_CACHE_DIR:-var/cache}/${APP_ENV:-prod}" tmp/cache/
```

It moves `var/cache/prod` to `/app/tmp/cache` (not to be confused with `/tmp`). Then, during deploy - `symfony-start` is called and it contains:
```
# copy cache if present
if [[ -d "tmp/cache/${APP_ENV:-prod}" ]]; then
    if [[ -z "${SYMFONY_APP_CACHE_DIR:-}" ]]; then
        if composer show symfony/flex >/dev/null 2>/dev/null; then
            SYMFONY_APP_CACHE_DIR="var/cache"
        else
            SYMFONY_APP_CACHE_DIR="app/cache"
        fi
    fi

    mkdir -p "${SYMFONY_APP_CACHE_DIR}"
    cp -Rp "tmp/cache/${APP_ENV:-prod}" "${SYMFONY_APP_CACHE_DIR}"
else
    symfony console cache:clear
fi
```

Thus copying already built cache for prod and calling `cache:clear` otherwise.

**Comment by fabpot** [comment]
So, I've just run the command and deployed it... and it works for me :)
https://main-bvxea6i-acswyqttenkqe.eu-3.platformsh.site/

**Comment by matthiaz** [comment]
:thinking: ok, I gotta admit, that build/deploy cache thing is a pretty cool thing. Thanks for clarifying that. 

I think I figured out why it isn't working for some customers. You are 100% right, the default instructions work perfectly fine because they use sqlite.

However, if you change your `.env` file to use postgres, or mysql, or whatever, then you get a failure on the cache:clear because then it does try to use the database during the build step :/ 

So what I think is happening, is that customers are changing the .env file from

```
DATABASE_URL=sqlite:///%kernel.project_dir%/data/database.sqlite
```

to
```
DATABASE_URL="mysql://main@database.internal:3306/main",
```

**Comment by fabpot** [comment]
But that's not the way it works ;) You should never set DATABASE_URL yourself. Symfony is doing it automatically for you. Let's move this discussion on Slack so that you can share more details with me.

**Comment by luimen6** [comment]
How should I set the database url?

**Comment by fabpot** [comment]
If you are using the configuration from the templates, there is nothing to do, the database URL is setup automatically via an environment variable. You can see what is defined by running `symfony var:export --multiline` from the app container (`symfony ssh`).
