### ISSUE TITLE
Docker ENV variable not found

### ISSUE THREAD

**Issue by TefDesign** [symfony-cli/symfony-cli#285]
When I start my local project, my Docker ENV variables are not found by Symfony CLI.
When I execute `symfony var:export --multiline`, I get the following output.

```BASH
export SYMFONY_APPLICATION_DEFAULT_ROUTE_HOST=en.wamiz.wip
export SYMFONY_APPLICATION_DEFAULT_ROUTE_PATH=/
export SYMFONY_APPLICATION_DEFAULT_ROUTE_PORT=443
export SYMFONY_APPLICATION_DEFAULT_ROUTE_SCHEME=https
export SYMFONY_APPLICATION_DEFAULT_ROUTE_URL=https://en.wamiz.wip/
export SYMFONY_DEFAULT_ROUTE_HOST=en.wamiz.wip
export SYMFONY_DEFAULT_ROUTE_PATH=/
export SYMFONY_DEFAULT_ROUTE_PORT=443
export SYMFONY_DEFAULT_ROUTE_SCHEME=https
export SYMFONY_DEFAULT_ROUTE_URL=https://en.wamiz.wip/
export SYMFONY_DOCKER_ENV=
export SYMFONY_PROJECT_DEFAULT_ROUTE_HOST=en.wamiz.wip
export SYMFONY_PROJECT_DEFAULT_ROUTE_PATH=/
export SYMFONY_PROJECT_DEFAULT_ROUTE_PORT=443
export SYMFONY_PROJECT_DEFAULT_ROUTE_SCHEME=https
export SYMFONY_PROJECT_DEFAULT_ROUTE_URL=https://en.wamiz.wip/
export SYMFONY_TUNNEL=
export SYMFONY_TUNNEL_ENV=
```

When I inspect my docker container database :
```
"Labels": {
    "com.docker.compose.config-hash": "170c91fd8716421e27e512a3b8cd9d623a8d4fdff74e4b1a49b95c369d3ea625",
    "com.docker.compose.container-number": "1",
    "com.docker.compose.depends_on": "",
    "com.docker.compose.image": "sha256:bd02430bb338544d999651aa695dfe7cedffb1257e7edf7067fb1cf23be4db22",
    "com.docker.compose.oneoff": "False",
    "com.docker.compose.project": "international-website",
    "com.docker.compose.project.config_files": "/Users/default-admin/travaux/international-website/docker-compose.yaml",
    "com.docker.compose.project.environment_file": "/dev/null",
    "com.docker.compose.project.working_dir": "/Users/default-admin/travaux/international-website",
    "com.docker.compose.service": "database",
    "com.docker.compose.version": "2.15.1"
}
```

Versions : 
- Docker : 20.10.23, build 7155243
- Docker compose : v2.15.1
- Symfony CLI : version 5.5.1

<img width="755" alt="image" src="https://user-images.githubusercontent.com/3847429/222736720-b25a6386-18ca-4a40-b61f-09c319b26b19.png">

**Comment by Kocal** [comment]
Hey, I'm having the same issue than my colleague @TefDesign. 

Like him, I'm using a MacBook M1 Pro, and I have the following app versions:
- Symfony CLI 5.5.1
- <img width="872" alt="Capture d’écran 2023-03-20 à 10 21 06" src="https://user-images.githubusercontent.com/2103975/226297797-539de68f-fc6e-4759-a468-28053045ac62.png">

And this is what outputs `symfony var:export --multiline`, which is a bit... empty: 
```
export APP_ID=01C0GAP4XEQ8HG6MGTJ7JB9EDT
export SYMFONY_DOCKER_ENV=
export SYMFONY_TUNNEL=
export SYMFONY_TUNNEL_ENV=
```

Note that our others colleagues @Kern046 and @Geekimo use the same environment development (same laptop, same app versions) but don't have this issue.

Is there any hint that can help us to fix this problem? Thanks!

**Comment by Kocal** [comment]
Well, after some debugging I've found that `/var/run/docker.sock` wasn't existing: 
<img width="1636" alt="Capture d’écran 2023-03-20 à 11 36 18" src="https://user-images.githubusercontent.com/2103975/226315829-43cb65ff-2d7c-4522-840d-7f58afe1adcf.png">
 
My other colleagues have this file, but @TefDesign and me have not, but re-creating manually through `sudo ln -s "$HOME/.docker/run/docker.sock" /var/run/docker.sock` made everything works again. 

Anyway, I think we can still print the `No /var/run/docker.sock found` when `--debug`

**Comment by tucksaun** [comment]
Is it possible that we "just" need to update our usage of the Docker library so that it accounts for this?
Or is it more a problem on your setup?

**Comment by Kocal** [comment]
Well, at my job we use [Kandji](https://www.kandji.io/) to pre-configure this and upgrade apps (and Docker), but as said before some of my colleagues didn't have any problem. :/ 

Anyway, Docker was running fine even without the `/var/run/docker.sock` file, this file does not seems mandatory.

I see in https://pkg.go.dev/github.com/docker/docker/client#pkg-constants that you can configure `DefaultDockerHost`, so maybe we can do a double-check?
- check for `unix:///var/run/docker.sock `, as now
- if necessary, check for `unix:///$HOME/.docker/run/docker.sock`

?

**Comment by Kocal** [comment]
Hum you're right about `DOCKER_HOST`, well I never add the use to configure it (myself or not), I know my `DOCKER_HOST` was always empty and it was working fine until this monday.

Anyway, I've added `export DOCKER_HOST="unix://$HOME/.docker/run/docker.sock"` in my `~/.zshrc` as it appears to be the cleanest solution for me, and it works perfectly.

Thanks for the advice :)
