### ISSUE TITLE
Directive 'track_errors' is no longer available in PHP

### ISSUE THREAD

**Issue by kriskoch** [symfony-cli/symfony-cli#289]
I installed symfony cli as per instructions on symfony.com version is 5.5.1

I installed it within a Ubuntu WSL2

I am running php 8.2
```
 php -v
PHP 8.2.1 (cli) (built: Jan 13 2023 10:42:44) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.1, Copyright (c), by Zend Technologies

```
Running command 
`symfony new --webapp test `
produces the following error 

```
Creating a new Symfony project with Composer
  (running /usr/local/bin/composer create-project symfony/skeleton /var/www/test --no-interaction)

PHP Fatal error:  Directive 'track_errors' is no longer available in PHP in Unknown on line 0

Fatal error: Directive 'track_errors' is no longer available in PHP in Unknown on line 0

  unable to run /usr/local/bin/composer create-project symfony/skeleton /var/www/test--no-interaction
```

If I run 
`/usr/local/bin/composer create-project symfony/skeleton /var/www/test--no-interaction  `
directly, it works fine  with no error.

**Comment by tucksaun** [comment]
As far as I can tell we don't use any specific PHP configuration at this stage.
Also, I don't find any reference to `track_errors` in the repositories.

So I would suspect this is part of your global PHP configuration at the system level.

**Comment by valkars** [comment]
I had the same problem and finally solved it. My localhost directory is ~/Web, there was old php.ini file which I copied for some reason from appropriate place to compare or smtg. And there was track_errors directive. Symfony cli somehow has found it and it is not good for PHP 8.3... I delete it and symfony works.

**Comment by kriskoch** [comment]
@valkars 
Oh wow! Thank you! after dealing with this for over a year, you are right, I also had an old php.ini file in the /var/www directory where I install new projects to.

doing php --ini doesnt reference the /var/www one 
and if I run php or composer on its own it doesnt use it, but for some reason the symfony command tries to use that php.ini file..

@tucksaun is this supposed tobe intentional? I dont really know go, but I looked through executor.go and I think  i see where it sets the ini path to be the cwd.

**Comment by fabpot** [comment]
It’s intentional.

**Comment by tucksaun** [comment]
it is indeed intentional.
this allows you to have per-project specific php settings.

and I would add that `symfony php` or `symfony composer` would use the `php.ini` in your working directory

**Comment by tucksaun** [comment]
@kriskoch if I understand correctly your issue is fixed? if so can we close this one?
