### ISSUE TITLE
Add an option to use dunglas / symfony-docker as skeleton

### ISSUE THREAD

**Issue by WebMamba** [symfony-cli/symfony-cli#290]
I use a lot this skeleton (https://github.com/dunglas/symfony-docker), and I think this is really popular in the community, so what do you think about adding an option to create a new project based on this skeleton?

I can totally work on it if you think this is interesting

**Comment by tucksaun** [comment]
Kevin's skeleton is not usable out-of-the-box using `composer create-project` which means it would require a lot of work for a small special case.

Also, Symfony CLI is not really useful in this skeleton context as PHP is included inside as well as the webserver and the skeleton takes care of running composer create-project.
You would probably be quicker running "git clone" and then not using the CLI at all.

**Comment by WebMamba** [comment]
Ok thanks for your answer I close the issue then.
