### ISSUE TITLE
Upper case extension does not supports

### ISSUE THREAD

**Issue by andrew-svirin** [symfony-cli/symfony-cli#292]
When creating 2 files `test1.TXT` and `test2.txt` and placing it in public directory, only `test2.txt` is accessible by http, than `test1.TXT` is not. Is such server behavior is correct?

**Comment by tucksaun** [comment]
the CLI code does discriminate for extension case as far as I can tell as I can reach filenames using both lower or uppercase extensions.
Though, I'm running macOS which is not sensible using a  case-sensitive FS by default, but maybe you do and this is the reason why it does not work?

**Comment by andrew-svirin** [comment]
This is default filesystem and I did not choose it.
And also some trouble with spaces in names.
Windows 10 + WSL + Ubuntu 20.04 + Docker (php:8.1.7-cli (5.15.90.1-microsoft-standard-WSL2))

For my case I figure out by renaming path and extension,.
