### ISSUE TITLE
Feature request: add environment variable to skip new version check

### ISSUE THREAD

**Issue by yesworld** [symfony-cli/symfony-cli#298]
Q: How do I disable the INFO of a new version?

```shell
$ symfony 

 INFO  A new Symfony CLI version is available (5.5.2, currently running 5.5.1).

       If you installed the Symfony CLI via a package manager, updates are going to be automatic.
       If not, upgrade by downloading the new version at https://github.com/symfony-cli/symfony-cli/releases
       And replace the current binary (symfony) by the new one.

```

**Comment by fabpot** [comment]
By upgrading. There is no other way right now.

**Comment by yesworld** [comment]
Just always update and that's it?
Or will there be some env parameter  where you can turn off the notification of this?

**Comment by fabpot** [comment]
Note that it's disabled in non-interactive mode.
For interactive sessions, I think we need to warn our users of new versions and make sure they update at their earliest convenience.

Why would you like to disable it and not upgrade to the latest version?

**Comment by yesworld** [comment]
I usually don't refresh every time if everything works fine. But unfortunately for me, as a perfectionist. It will be distracting every time I start the ```$ symfony server:start```.

Wouldn't it be better to make it informative for minor versions?

P.s. If I'm the only one, then I suggest closing Issue. I don't want to waste your time.

**Comment by xorik** [comment]
I was also looking for this feature.

My reasoning:
Those messages distract me from my current task so I lose my focus, forget what I was doing, etc. It might be annoying. Plus in 99% this update won't change anything for me.

Another reason is that it's not common for terminal tools ask for updates. Imagine you run `git` and it ask you to update itself.

I agree disabling updates is terrible idea, but maybe make it less frequent, e.g. promote major releases, or suggest only if current version is 3-6 months old.

**Comment by cafferata** [comment]
> Why would you like to disable it and not upgrade to the latest version?

Because it doesn't add anything when I update automatically by [homebrew-autoupdate](https://github.com/Homebrew/homebrew-autoupdate).

**Comment by fabpot** [comment]
I like the reasoning here: https://github.com/symfony-cli/symfony-cli/pull/301#issuecomment-1488924755
At least, I don't think it makes sense for me to spend more time on this issue.

**Comment by fabpot** [comment]
#309 limits the version check once per day, I think this is a good compromise.
