### ISSUE TITLE
Slow response when no arguments are passed

### ISSUE THREAD

**Issue by javiereguiluz** [symfony-cli/symfony-cli#30]
When running `symfony` without any arguments, I'd expect an instantaneous (or at least, very fast) response. Instead, it took more than 4 seconds in a recent MacBook Pro:

<img width="895" alt="symfony-execution" src="https://user-images.githubusercontent.com/73419/148741109-f13f0f9c-40fa-43d2-bc3e-d69115b7916a.png">

The previous closed-source version was much faster, so maybe someone from the community can investigate what's introducing a delay in this open-source version. Thanks!

**Comment by fabpot** [comment]
I don't have the issue, maybe related to Docker again? This needs to be investigated.

**Comment by henrikac** [comment]
I get the following output when I run `time symfony` on fedora 35 with `Symfony CLI version 5.2.2`

```
real    0m0.018s
user    0m0.014s
sys     0m0.008s
```

**Comment by javiereguiluz** [comment]
I've just upgraded to 5.2.2 version and the command is again instantaneous, so I'm closing this issue:

```
$ time symfony
Symfony CLI version 5.2.2 (c) 2017-2022 Symfony SAS (2022-01-23T18:01:02Z - stable)
Symfony CLI helps developers manage projects, from local code to remote infrastructure

[...]

0.01s user
0.01s system
80% cpu
0.029 total
```
