### ISSUE TITLE
Remove political statement

### ISSUE THREAD

**Issue by markwatney2016** [symfony-cli/symfony-cli#304]
I think it is not appropriate to print political statements when the Symfony CLI is used. A request for humanitarian help for the Ukrainian people would in my view be more appropriate than to take one side of the conflict by using the `#StandWithUkraine` hashtag and print `Support Ukraine` – supporting a country/government is not the same as supporting a country's people.

<img width="862" alt="grafik" src="https://user-images.githubusercontent.com/22563689/230898662-7f4958f0-3134-4033-8fce-aa4be905d311.png">

Did the Symfony project print similar political statemens before or will it do so in the future? There are a lot of horrific conflicts going on in the world. Will the Symfony project take sides there as well?

**Comment by markwatney2016** [comment]
This seems more appropriate to me:

<img width="1433" alt="grafik" src="https://user-images.githubusercontent.com/22563689/230912924-a3c5180f-df92-4911-805c-cb774b0c00a8.png">

**Comment by markwatney2016** [comment]
I am sorry if my request triggered you. To be honest, I would have preferred not to be schooled by you about how I should behave ("let Russia know instead").

**Comment by markwatney2016** [comment]
I am glad, that that political statement was finally removed with https://github.com/symfony-cli/symfony-cli/commit/7b1629faea560cc8b0c917872fae3ca62d13f250.

**Comment by webknjaz** [comment]
> This has been an ongoing debate on the Internet since the beginning of this war 🙄

Not true. In 2013/2014 people didn't care about the war, this only suggests reverting to ignoring the ethnic cleansing so everyone outside of Ukraine can feel better about themselves.

**Comment by webknjaz** [comment]
> political statement

It's not a political statement, though. People like to do term substitution. But when you get robbed, do your neighbors say that it's politics and therefore it's unfair to notice you, because it's happening to other people?

**Comment by webknjaz** [comment]
FWIW I shared some of the things you call politics that are actually just life here: https://github.com/symfony/symfony/pull/53238#issuecomment-1874284912.

**Comment by sokil** [comment]
its funny whan you call politics this:
* killing of people in Bucha and other cities, mass graves
* _Complety_ destroyed cities Bakhmut, Marinka
* execution of prisoners of war
* hundreds of thousands killed civils in Mariupol
* 7500 missiles were launched on the territory of Ukraine
* 3800 drones Shahed
* millions of refugees
* all nomenclature of missles except nuclear (yet)

**Comment by webknjaz** [comment]
Added more explanation/examples of a non-inclusive behavior here: https://github.com/vshymanskyy/StandWithUkraine/issues/262#issuecomment-1874358161
