### ISSUE TITLE
Should `Server` header be added to responses?

### ISSUE THREAD

**Issue by cedric-anne** [symfony-cli/symfony-cli#306]
I work on an open source software that runs on PHP. We collect anonymized data to be able to do some statistics about execution environment of our software. When data is collected inside CLI context (typically a crontask), we cannot rely on `$_SERVER['SERVER_SOFTWARE']` information, and we try to fetch this information by doing a request to the application base URL in order to get it from the `Server` header.

Applications served by `Symfony CLI` does not have this header in their response. Should it be added?
Having such information may result in security issues, but, as stated during execution, it `MUST never be used in a production setup`.

**Comment by cedric-anne** [comment]
> It will not make your life easy

Honestly, we just have a few missing values in our stats reports, but that is not really a problem. Indeed, many people already make this information unavailable on their production environment, so we have to deal with it anyway.

It was more out of curiosity that I would have liked to have `Symfony CLI` related data in our reports, but I guess our application should very rarely run on it.

**Comment by tucksaun** [comment]
> It was more out of curiosity that I would have liked to have Symfony CLI related data in our reports

I would have been curious as well 😃 

Closing for now for the reason mentioned before.
