### ISSUE TITLE
run -d does not act as expected

### ISSUE THREAD

**Issue by YetiCGN** [symfony-cli/symfony-cli#307]
I was delighted to find the section "[Long-Running Commands](https://symfony.com/doc/current/setup/symfony_server.html#long-running-commands)" in the documentation. I thought it would be a great replacement for running a command on Linux in the background with `&` but also piping to some logfile, which results in a lengthy command.

However, it seems that this feature is only applicable to the mentioned use case: Starting a watcher job in the background. If I run any other command that eventually terminates, it is restarted and restarted again:

```
$ symfony run -d yarn install
Stream the logs via symfony server:log
$ symfony server:log
Following Web Server log file (/home/jwagner/.symfony5/log/4408ff9e1a3081db80a1b6821cae37c343b7f8cd.log)
Following yarn install log file (/home/jwagner/.symfony5/log/4408ff9e1a3081db80a1b6821cae37c343b7f8cd/b8d744ed21be73ce22496a918c6bfd5548e56388.log)
[Worker yarn] yarn install v1.22.19
[Worker yarn] [1/4] Resolving packages...
[Worker yarn] yarn install v1.22.19
[Worker yarn] [1/4] Resolving packages...
[Worker yarn] yarn install v1.22.19
[Worker yarn] [1/4] Resolving packages...
[Worker yarn] yarn install v1.22.19
[Worker yarn] [1/4] Resolving packages...
[Worker yarn] yarn install v1.22.19
[Worker yarn] [1/4] Resolving packages...
^C
```
It just runs again and again. The comment "# and you can also check if the command is still running" is also misleading, the command will always be running.

If this is the intended behavior because this command should only be used for perpetual background jobs that might eventually crash and then are restarted automatically, fine. But I think it could be so much more if commands would terminate after being done.

**Comment by tucksaun** [comment]
This is indeed the intended use as running a "slow" command without blocking the terminal can be easily achieved using `&` or `nohup`. This is also why the option is called "daemon" and not "background".

> The comment "# and you can also check if the command is still running" is also misleading, the command will always be running.

It's true the sentence can be misleading but is not false either as the command could be not running because pending a restart or stopped from the outside

**Comment by tucksaun** [comment]
So I have the feeling is indeed wrong here given the code wrote I suspect some bug introduced and/or refactoring removed the necessary bits.
I opened a PR (#308) with what I have been able to remember so far but it might require more fiddling.
Would you have a change to give it a go locally and see how it works for you?

**Comment by YetiCGN** [comment]
@tucksaun Thanks! I can confirm that in Symfony CLI 5.7.2 the command is not executed in a loop anymore. However, the  `symfony` process also doesn't terminate:

    $ ps auxf | grep yarn
    jwagner  12530  0.0  0.0  16540  1276 tty1     S    16:58   0:00      \_ grep --color=auto yarn
    jwagner  11978  0.0  0.0 1246800 8176 ?        Ssl  16:52   0:00 symfony run -d yarn install
    jwagner  12044  0.0  0.0 1247056 8152 ?        Ssl  16:53   0:00 symfony run -d yarn install

This leaves an idling process for every run, which is not too bad but probably unintended?

**Comment by tucksaun** [comment]
@YetiCGN I'm sorry, the way I formulated my idea was probably misleading as I your issue lead me to discover that a specific use case was not supported anymore.

Your use case is not really currently supported as you can already do it by using native OS syntax: `symfony run yarn install &`
The only true use case to use `-d` with a single time command is when one uses `--watch` which will restart the command when needed.
