### ISSUE TITLE
Provide more debugging information?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony-cli/symfony-cli#31]
In the previous version, you could pass `-v`, `-vv`, `-vvv`, `-vvvv` and even `-v=5` to get very detailed debug info of the command execution.

That came in handy when debugging issues like #30 because you could see exactly what's being executed.

In the new version of the tool, these debugging options seem to have been removed. Thanks.

**Comment by fabpot** [comment]
It works in the exact same way, so you have the same debugging information as before.

**Comment by fabpot** [comment]
Makes sense to me as the OSS one does not call symfony.com. But if run a command that makes HTTP calls, you would get the same kind of logs. Also, keep in mind that any command that is related to the cloud is now proxied to the Platform.sh CLI, so, no logs there.
Closing as there is nothing to fix here.
