### ISSUE TITLE
Improve config file parsing robustness

### ISSUE THREAD

**Issue by rhubinak** [symfony-cli/symfony-cli#315]
Have .env file with the following line (note space at the end):
```
DATABASE_URL="mysql://main:main@database.internal/main?serverVersion=10.11" 
```
On `symfony deploy` this results in:
```
  The ".platform/services.yaml" file defines
  a "mariadb" version 10.11 database service
  but the ".env" file requires version 10.11" .
  Before deploying, fix the version mismatch.
```
The reason is that the [config parser](https://github.com/symfony-cli/symfony-cli/blob/main/commands/db_versions.go#L63) takes the trailing whitespace into account. Short term fix would be to trim whitespace from the end of the string. Long term would be to consider some config parsing library such as [viper](https://github.com/spf13/viper).

**Comment by fabpot** [comment]
Trimming seems like a good option. Do you want to work on a PR?

**Comment by rhubinak** [comment]
Sure

**Comment by fabpot** [comment]
@rhubinak It looks like @tucksaun was already working on a fix :)

**Comment by tucksaun** [comment]
Yep, sorry about that I saw your comment when coming to comment it was going to be fixed soon 😅

**Comment by rhubinak** [comment]
Please don't ever apologize for fixing stuff :grin:
