### ISSUE TITLE
Bind Address causes popup on mac

### ISSUE THREAD

**Issue by gempir** [symfony-cli/symfony-cli#319]
It would be great if either the bind address could be specified via a option or it just defaults to 127.0.0.1

Currently symfony serve seems to default to 0.0.0.0 which means external connections are allowed and it will cause this annoying popup on macOS 13.3.1 each time it's started. 

From a security standpoint it makes more sense anyway to default to 127.0.0.1
The usecase of external connections is very slim, IMO. 

![image](https://user-images.githubusercontent.com/9765622/235857147-e648acf6-3a71-4a56-8e1b-2397fc5050a7.png)

**Comment by henrikac** [comment]
I just upgrade my MacBook Pro M1 to 13.3.1 and Symfony CLI to 5.5.4 (installed with brew) and I am not experiencing this.

Which version of the CLI are you using?

**Comment by gempir** [comment]
Tested on 5.4.19 AND 5.5.4 on macOS 13.3.1 (a)

Both are throwing the warning.

The full command I'm calling is just:
`symfony serve --port 8000`

**Comment by ngrie** [comment]
Usually I saw this popup only once after every update of the CLI tool. After switching to an M2 MacBook, I indeed get the popup every time I run `symfony server:start`.

macOS 13.4.1, Symfony CLI version 5.5.6

**Comment by gempir** [comment]
My device is an M1 Max maybe Apple Silicon is different than Intel here

**Comment by ngrie** [comment]
I just found #117, this even is mentioned in the docs: https://symfony.com/doc/current/setup/symfony_server.html#getting-started

This does not fix your security concerns about allowing external connections, but at least stops those popups.
