### ISSUE TITLE
Cannot install/renew a local CA

### ISSUE THREAD

**Issue by juanOS85** [symfony-cli/symfony-cli#32]
Every time I execute `server:ca:install`, `server:ca:install --force` or `server:ca:install --renew` to install/renew a local CA for a project the command gets stuck after requesting to enter the root password. 

I even removed the `~/.symfony5` directory but that didn't help at all.

This started to happen after updating to Symfony CLI version 5.0.8.

Environment:
- M1 MacBook Pro
- macOS 12.1
- PHP 7.4
- Symfony 4.4.33
- Symfony CLI 5.0.8 (Homebrew)

**Comment by Kocal** [comment]
Not sure if it's related, but did you removed the previous CA installed by the [previous Symfony CLI](https://github.com/symfony/cli)?

**Comment by juanOS85** [comment]
@Kocal oops... I forgot to mention I did that as well thank you for mention it., 

I executed `server:ca:uninstall` and I get output:

```
The local CA is now uninstalled from the system trust store(s)!
The local CA is now uninstalled from the Firefox trust store(s)!

 [OK] The local Certificate Authority has been uninstalled
```

And after that I executed again `server:ca:install` without any luck.

**Comment by juanOS85** [comment]
Ok, after running some more tests, I identified the local CA are actually being installed/renewed, but the `server:ca:install` command doesn't finish its execution:

<img width="707" alt="Screen Shot 2022-01-10 at 11 14 10" src="https://user-images.githubusercontent.com/201116/148799519-5e12a8ce-fb8e-41d1-b433-cc9a59a867be.png">

**Comment by juanOS85** [comment]
And now I'm getting this on Google Chrome:

<img width="815" alt="Screen Shot 2022-01-10 at 11 16 40" src="https://user-images.githubusercontent.com/201116/148799807-2861d5a4-bd5f-4788-9382-74a8bf48424f.png">

**Comment by juanOS85** [comment]
Restarting macOS did the trick for this 🤦🏻‍♂️
