### ISSUE TITLE
DB version check since release 5.5.3 blocks deployment with mariadb

### ISSUE THREAD

**Issue by swmeer** [symfony-cli/symfony-cli#321]
When using MySQL on platform.sh, MariaDB is used. The version should be defined as `10.6`, like described in the platform.sh docs:
https://docs.platform.sh/add-services/mysql.html#supported-versions
> The service types mariadb and mysql both refer to MariaDB. 

But symfony requires a mariadb prefix like `mariadb-10.6` or `mariadb-10.6.12`, like described in de docs here:
https://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration

> If you are running a MariaDB database, you must prefix the server_version value with mariadb- (e.g. server_version: mariadb-10.4.14).

When having symfony configured with `mariadb-10.6` or `mariadb-10.6.12` and platform.sh as '10.6', which used to work perfectly, now results in the following error message when deploying the application:
`The ".platform/services.yaml" file defines a "mariadb" version 10.6 database service  but the ".env" file requires version mariadb-10.6. Before deploying, fix the version mismatch.`

Should I configure it differently or is the [newly added DB check](https://github.com/symfony-cli/symfony-cli/commit/5e6c0fa47801925d67d3ef40efe108b0395842d7) to strict to allow for this difference to exist?

**Comment by fabpot** [comment]
Should be fixed by #322

**Comment by swmeer** [comment]
@fabpot, thank you! I can confrm it fixes the issue.
