### ISSUE TITLE
Current distribution release and version is not yet supported for ALPINE::3.18

### ISSUE THREAD

**Issue by engharb** [symfony-cli/symfony-cli#323]
Hi,
Security-check fails by running `curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.alpine.sh' | bash`.

![image](https://github.com/symfony-cli/symfony-cli/assets/7124220/796e0e86-4ca4-45af-ae42-82d8e4c4e8b4)

I think you need to update your repo with the latest ALPINE release v3.18.0.

Thanks,

**Comment by baris1892** [comment]
Note: this happens to me also on Ubuntu 19.10, see the attached image.
![image](https://github.com/symfony-cli/symfony-cli/assets/4377975/b1dd96a0-7c6c-4f44-8636-796f6a7d2aed)

**Comment by tucksaun** [comment]
@engharb  if I remember correctly, cloudsmith only regenerate repositories when we publish new release and as Alpine 3.18 is quite recent, there have been no recent releases since then, so you will probably need to wait until a new release.

**Comment by tucksaun** [comment]
@baris1892 you need to use the `https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh` URL not the alpine one

**Comment by engharb** [comment]
thank you @tucksaun. 
We downgrade the release version of the distribution::alpine.
For example: `curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.alpine.sh' | distro=alpine codename=3.17 bash`
