### ISSUE TITLE
Can't install symfony-cli for alpine from Cloudsmith

### ISSUE THREAD

**Issue by grogou** [symfony-cli/symfony-cli#324]
Hi there.

Guess Cloudsmith is down or something else.

error log
```
 => ERROR [dev 16/18] RUN apk add --no-cache bash &&     bash -c "$(curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.alpine.sh')" &&     apk add symfony-cli                                                                                   2.2s 
------
 > [dev 16/18] RUN apk add --no-cache bash &&     bash -c "$(curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.alpine.sh')" &&     apk add symfony-cli:
#0 0.304 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
#0 0.595 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
#0 0.854 OK: 653 MiB in 129 packages
#0 1.591 Executing the  setup script for the 'symfony/stable' repository ...
#0 1.591
   OK: Checking for required executable 'curl' ...
   OK: Detecting your OS distribution and release using system methods ...
#0 1.602  ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
#0 2.202  >>>>: version, or codename via environment variable. E.g., to specify a distro
#0 2.202  >>>>: such as Alpine (v3.8), use the following:
#0 2.202  >>>>:
#0 2.202  >>>>:   <curl command> | distro=alpine version=3.8.0 codename= sudo -E bash
#0 2.202  >>>>:
#0 2.203  !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
#0 2.203  !!!!:
#0 2.203  !!!!: You can contact Symfony for further assistance.
#0 2.203  !!!!:
#0 2.203  !!!!: URL: https://github.com/symfony-cli/symfony-cli
#0 2.203  !!!!:
#0 2.203  !!!!: Last 20 log lines from .csm_setup_XXXjpHJKh (might not be errors, nor even relevant):
#0 2.203  !!!!:
#0 2.204
------
failed to solve: process "/bin/sh -c apk add --no-cache bash &&     bash -c \"$(curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.alpine.sh')\" &&     apk add symfony-cli" did not complete successfully: exit code: 1
```

Same happens in live server, guess it is not environment related issue.

**Comment by grogou** [comment]
Thank you very much for response 🥇

**Comment by juliolopeztorres** [comment]
Same here trying to install inside docker container either from `php:8.3-fpm-alpine`, `php:8.2-fpm-alpine` or `php:8.1-fpm-alpine`. 

In `7.4`, the `symfony-cli` can be installed. 

If I run the image the step before `RUN curl ...` and execute it manually, the repository is added to `/etc/apk/repositories` successfully and I can proceed. I don't know why the `RUN` command do not work. 

Also tried with `wget` + installer as `symfony.com` download section mentions. No luck. 

Could anyone provide a suggestion? 

Thank you!

**Comment by tucksaun** [comment]
a new version of alpine has been released recently, cloudsmith repos might not be up-to-date yet.

in a Docker context I would recommend to use `COPY --from=ghcr.io/symfony-cli/symfony-cli:latest /usr/local/bin/symfony /usr/local/bin/symfony` instead as it is more cross platform (not alpine dependant), should be faster to run because no apk index to update and simple because there's no cleanup process to keep your layers tidy

**Comment by yguedidi** [comment]
@tucksaun is this way on installing Symfony CLI in a Docker context documented somewhere? didn't find it.
Maybe it could be a new section Docker in the Linux tab of https://symfony.com/download?

**Comment by tucksaun** [comment]
> @tucksaun is this way on installing Symfony CLI in a Docker context documented somewhere? didn't find it.
> 
> Maybe it could be a new section Docker in the Linux tab of https://symfony.com/download?

As Docker is not strictly limited to Linux (for the host) I would instead add a Docker dedicated tab explaining one can run the image or use the COPY method to install it within their own image. WDYT @javiereguiluz ? Possible ?
