### ISSUE TITLE
cli changes alternatives symlinks

### ISSUE THREAD

**Issue by wesnick** [symfony-cli/symfony-cli#327]
I have a basic Ubuntu installation with sury PPA and 2 versions of PHP installed `7.4` and `8.2`.  I use alternatives to manage which version I am currently using.  Every time I use symfony cli, it changes my version to `7.4` regardless of the values of `FORCED_PHP_VERSION` or `.php-version`.  My expectation is that the symfony-cli should not change my symlinks.

```bash
05:41 $ php -v
PHP 8.2.6 (cli) (built: May 12 2023 06:24:00) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.6, Copyright (c), by Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans
```
```bash
05:41 $ ll /etc/alternatives/php
lrwxrwxrwx 1 root root 15 May 24 05:41 /etc/alternatives/php -> /usr/bin/php8.2*
```

```bash
05:42 $ cat .php-version 
8.2
```

```bash
05:42 $ symfony local:php:list
[sudo] password for myuser:  ◓  
+---------+-----------+------------+-----------------+----------------+---------+---------+
| Version | Directory |    PHP     |       PHP       |      PHP       | Server  | System? |
|         |           |    CLI     |       FPM       |      CGI       |         |         |
+---------+-----------+------------+-----------------+----------------+---------+---------+
| 7.4.33  | /usr      | bin/php7.4 | sbin/php-fpm7.4 | bin/php-cgi7.4 | PHP FPM | *       |
| 8.2.6   | /usr      | bin/php8.2 | sbin/php-fpm8.2 | bin/php-cgi8.2 | PHP FPM |         |
+---------+-----------+------------+-----------------+----------------+---------+---------+

The current PHP version is selected from .php-version from current dir: /home/myuser/myproject/.php-version

To control the version used in a directory, create a .php-version file that contains the version number (e.g. 7.2 or 7.2.15),
or define config.platform.php inside composer.json.
If you're using Platform.sh, the version can also be specified in the .platform.app.yaml file.
```

It is not visible here, but `8.2.6` is highlighted in the console, however, just listing the versions has changed my symlinks

```bash
05:42 $ php -v
PHP 7.4.33 (cli) (built: Feb 14 2023 18:31:54) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies
    with Xdebug v3.1.6, Copyright (c) 2002-2022, by Derick Rethans
```

```bash
05:42 $ ll /etc/alternatives/php
lrwxrwxrwx 1 root root 15 May 24 05:42 /etc/alternatives/php -> /usr/bin/php7.4*
```

This also occurs for every other command I use with symfony cli.  `symfony serve` will start a webserver in my desired version, but it changes my alternatives symlinks

**Comment by tucksaun** [comment]
I couldn't manage to reproduce your issue with a fresh new installation of Ubuntu and Ondřej PPA.
But this is not really surprising as the CLI is not changing any system symlinks (at least it is not supposed to).

But the CLI is executing every PHP installation found to determine the version, so a clue might be that you have something in place to switch `/etc/alternatives/php` depending on the last version used?
I'm particularly inclined to trust this could be the cause given the `sudo` prompt I see when you run `symfony local:php:list`

**Comment by wesnick** [comment]
I do have a simple script to update alternatives that looks like this, which is just a script
```bash
sudo update-alternatives --set php /usr/bin/php8.2
sudo update-alternatives --set php-cgi /usr/bin/php-cgi8.2
sudo update-alternatives --set phar /usr/bin/phar8.2
sudo update-alternatives --set phar.phar /usr/bin/phar.phar8.2
sudo update-alternatives --set phpize /usr/bin/phpize8.2
sudo update-alternatives --set php-config /usr/bin/php-config8.2
sudo update-alternatives --set php-fpm.sock /run/php/php8.2-fpm.sock
```

But the symfony cli command prompts me for sudo privs, why does this happen when I am just asking to list ?

**Comment by tucksaun** [comment]
As I said:
> the CLI is executing every PHP installation found to determine the version

**Comment by wesnick** [comment]
You were correct, using the verbose flag `-vvv` I was able to see where privilege escalation was occurring and found a script I had forgotten about in `/usr/local/bin` that was switching alternatives symlinks.  Thanks for the comments that steered me in the right direction.
