### ISSUE TITLE
Not detecting PHP Binary

### ISSUE THREAD

**Issue by michaelotoole** [symfony-cli/symfony-cli#33]
Just moved over to the new open-source symfony-cli, but `symfony local:php:refresh/list`, does not find the local php versions installed.

I have since re-installed the latest close source release and the commands work fine.

I am also getting the following panic when creating a new project (assuming it is because the php binaries are not found):

`panic: runtime error: invalid memory address or nil pointer dereference`

As with issue #31, cannot use any debugging options to see exactly where the cli is looking:

Running on:

- Mac OS X 12.1 - Intel
- Symfony CLI: 5.0.8
- `php -v` is 8.0.14 - installed via Homebrew

When I reverted back to Symfony 4.28.1, without changing anything else this is working fine.

**Comment by kstefanini** [comment]
Hi! I have kind of the same problem on Ubuntu with version from apt repository. Php7.3 is not detected while php8.0 is detected. Using symfony-cli v4, both version are detected.

**Comment by fabpot** [comment]
It's not related to #31, there was "just" a typo here: https://github.com/symfony-cli/phpstore/commit/bd49509f07863b9a929c2800b9cc1d45de89c270
All fixed now.
While I'm at it, I've also fixed the log output to be more friendly (it was JSON only right now). See #34

**Comment by fabpot** [comment]
The panic you see will also be fixed by the patch.
