### ISSUE TITLE
Support for streaming

### ISSUE THREAD

**Issue by weaverryan** [symfony-cli/symfony-cli#330]
Hi!

I'm experimenting with a dev-only implementation of HMR for AssetMapper where a Symfony endpoint "streams" information about changes made to CSS files. However, like #67, I don't believe the `symfony` binary server supports streams: the same code that streams with `php -S` does not stream using `symfony serve`.

Is something that would be possible to add? Without it, in practice, for HMR, I think we'd need to require the user to install Mercure, which would be a much higher hurdle.

Thanks!

**Comment by tucksaun** [comment]
Hi Ryan!

IIRC the golang proxy does buffer responses and we use this in order to be able to tweak the WDT.
But we can probably do something about streaming if we determine the right conditions to say "this response is a streamed one".

Would you have some code available for me to thinker with?

**Comment by weaverryan** [comment]
Yes! Let me get you some code right now...

**Comment by weaverryan** [comment]
And... here's some test code: https://github.com/weaverryan/streaming-test

I've verified that this *does* stream with `php -S`. I'm using the `Content-Type` header of `text/event-stream` in this case, which could be a clear indicator. It would not catch all cases, but would catch one big category.

Thanks :)

**Comment by tucksaun** [comment]
ok so the culprit is not the Golang webserver but some buffering done the CLI (the WDT tweaking to be accurate).
But also streaming from the FPM client is not working at the moment.
I started to do some work locally and manage to get it working by disabling tweaking and adding some dirty sauce so this will be possible but will require a bit of work, stay tuned :)

**Comment by weaverryan** [comment]
> I started to do some work locally and manage to get it working by disabling tweaking and adding some dirty sauce so this will be possible but will require a bit of work, stay tuned :)

Ha! Ok, thank you! As we talked about earlier, it could probably be ok to stream only if the response has a certain content-type, if that makes things easier (well, at least, selfishly for me, that would be enough).

**Comment by weaverryan** [comment]
Friendly nearly-end-of-summer ping! 😄

**Comment by weaverryan** [comment]
Hey buddy o/

I think we talked and there MIGHT be an easy solution for this? Iirc, we could even possibly disable the code that prevents streaming *if* a certain request header is sent? What I want this for is still an experiment, but assuming it worked (HMR), it'd be a great thing to have for the 6.4 release / SymfonyCon.

Thanks!

**Comment by tucksaun** [comment]
@weaverryan sorry for delay 😞  but here is an almost ready PR: #371 😃
