### ISSUE TITLE
Symfony CLI version

### ISSUE THREAD

**Issue by danian3wa** [symfony-cli/symfony-cli#337]
I've updated the Symfony CLI to 5.5.8 and now my application is not working anymore, how to downgrade to 5.5.7 on mac os? please help.

An exception has been thrown during the rendering of a template ("An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't1.name' in 'field list'").

**Comment by fabpot** [comment]
It's probably not related to Symfony CLI.

**Comment by danian3wa** [comment]
> It's probably not related to Symfony CLI.

Thank you for your answer, I found out what the problem was
