### ISSUE TITLE
# unable to fetch the response from the backend: unexpected EOF

### ISSUE THREAD

**Issue by Kinqdos** [symfony-cli/symfony-cli#348]
Since the last brew update me and my team are only getting this error when working with local server via symfony-cli. We use `symfony server:start` on mac os. On windows everything works fine this just happens on mac.
<img width="1171" alt="image" src="https://github.com/symfony-cli/symfony-cli/assets/62080449/1f32fb9d-a97f-418e-98b1-7fb727051df3">

The logs from the console just show the same error:
<img width="1172" alt="image" src="https://github.com/symfony-cli/symfony-cli/assets/62080449/caa8d4fe-7763-417e-bcc4-e7aea8977b3e">

Can anyone help me or at least tell where I find a more detailed log? I mean wich file is even meant with EOF. I have nothing to start with.

**Comment by fabpot** [comment]
Reading the logs here, it seems PHP-FPM crashes for some reasons (`child xxx exited on signal 11`).

**Comment by Kinqdos** [comment]
Turns out it is an issue with doctrine. `getRepository(InetOrgPerson::class)->find($guid)` causes the problem. Can you tell me where to get a more detailed log? Perhaps the one thats causing the eof

**Comment by B-Galati** [comment]
@Kinqdos how did you find that the issue is related to Doctrine? Would love to help getting this fixed quickly :+1:

**Comment by htaoufikallah** [comment]
I am facing the same issue. I found out that it is related to postgres only over http while it works just fine via cli.
To confirm this, I tested the same code with mysql, and it worked just fine without any issue.

To confirm that it is only related to php over http, I tried to connect to the same postgres with nodejs and works just fine without any issue via cli and over http.

Config:
Macos monterey
Intel based
Php8.2
Postgres 15
Symfony 6.2
Doctrine orm 2
Doctrine dbal 3

**Comment by Kinqdos** [comment]
@B-Galati I throwed in exception before the error showed up an made my way through the code until I reached a doctrine ->find(...) call. I tested a bit more and found out that the error only shows up when doctrine is involved.
@htaoufikallah Youre absolutely right Im using postgres too. The interesting thing is, Im using two databases in my code. One with postgres version 9 and one with version 12. (Please dont blame for the outdated version, wasnt my decision not to upgrade). The error is only related to newer versions. With version 9 everything works like a charm. I also tested version 16 (newest) but got the same problem. So everything from 12 onwards seems to cause the problem.

Hopes this helps to fix the bug.

**Comment by Kinqdos** [comment]
Missclick

**Comment by SiM07** [comment]
I've the same issue and use postgres too.

Macos Sonoma 14.1 (Mac M1)
SF 6.2
Postgres (15) in docker
Doctrine 

When I restart SF Cl it works just for few http calls and i need to restart.

**Comment by B-Galati** [comment]
Thank you everyone! It looks like the root cause is linked to Homebrew and someone has found a proper workaround: https://github.com/Homebrew/homebrew-core/issues/137431#issuecomment-1763383159.

**Comment by fabpot** [comment]
Let's close here then. Thank you @B-Galati.

**Comment by cfoehrdes** [comment]
We have the same issue on several Mac in the office and the workaround from the ticket @B-Galati mentioned did not help. The workaround requires modifying the `www` php-fpm pool config but symfony-cli seems not to use the config of the php-fpm shipped with homebrew.

As you see in the output of `symfony server:start -d` the pool config (in my case stored at `/opt/homebrew/etc/php/8.1/php-fpm.d/www.conf`) is ignored and symfony-cli starts the server with its own (probably at launch generated) pool config.

```
Local Web Server
    Listening on https://127.0.0.1:8000
    The Web server is using PHP FPM 8.2.11 (from .php-version from current dir: /Users/xxxxx/Projects/test/.php-version)

Local Domains
    https://dam.wip

Workers
    PID 10483: /opt/homebrew/Cellar/php/8.2.11/sbin/php-fpm --nodaemonize --fpm-config /Users/xxxxx/.symfony5/php/79a30a3e0cd78eac3cab49aeab52b9c809e6a157/fpm-8.2.11.ini --force-stderr (watching /Users/xxxxx/Projects/test/php.ini/)
```

In this case it uses `.symfony5/php/79a30a3e0cd78eac3cab49aeab52b9c809e6a157/fpm-8.2.11.ini` which contains nothing from my systems www.conf.

@fabpot Is there a way to impact the `fpm-8.2.11.ini` content?

**Comment by cfoehrdes** [comment]
The `fpm-8.2.11.ini` is equivalent with `www.conf` pool config and not the `php.ini`

**Comment by floriansemm** [comment]
to add a `php.ini` just overwrites php options as far as I understood from the documentation. The question was how to overwrite php-fpm options/settings.

**Comment by fabpot** [comment]
Changing the default FPM is not possible (at least today).
It's defined here: https://github.com/symfony-cli/symfony-cli/blob/main/local/php/fpm.go
Before making it configurable, can someone test the change form #361?
You can download the complied binary here: https://github.com/symfony-cli/symfony-cli/actions/runs/6612184644?pr=361 (the `binaries.zip` file contains all binaries).

**Comment by VoigtK** [comment]
I can confirm. The compiled binaries fixed the problem!

**Comment by cfoehrdes** [comment]
It is also working for me, thank you!

**Comment by fabpot** [comment]
v5.6.1 with the fix has been released now.
