### ISSUE TITLE
Docker integration fails [SYMFONY_DOCKER_ENV=NULL]

### ISSUE THREAD

**Issue by DigitalTimK** [symfony-cli/symfony-cli#350]
# Problem
I just realized an issue with the symfony / docker integration. In this case the environment variable SYMFONY_DOCKER_ENV variable was empty/null but the value "1" should be shown.

```
❯ symfony var:export --multiline
export SYMFONY_APPLICATION_DEFAULT_ROUTE_HOST=127.0.0.1:8000
export SYMFONY_APPLICATION_DEFAULT_ROUTE_PATH=/
export SYMFONY_APPLICATION_DEFAULT_ROUTE_PORT=8000
export SYMFONY_APPLICATION_DEFAULT_ROUTE_SCHEME=https
export SYMFONY_APPLICATION_DEFAULT_ROUTE_URL=https://127.0.0.1:8000/
export SYMFONY_DEFAULT_ROUTE_HOST=127.0.0.1:8000
export SYMFONY_DEFAULT_ROUTE_PATH=/
export SYMFONY_DEFAULT_ROUTE_PORT=8000
export SYMFONY_DEFAULT_ROUTE_SCHEME=https
export SYMFONY_DEFAULT_ROUTE_URL=https://127.0.0.1:8000/
export SYMFONY_DOCKER_ENV=
export SYMFONY_PROJECT_DEFAULT_ROUTE_HOST=127.0.0.1:8000
export SYMFONY_PROJECT_DEFAULT_ROUTE_PATH=/
export SYMFONY_PROJECT_DEFAULT_ROUTE_PORT=8000
export SYMFONY_PROJECT_DEFAULT_ROUTE_SCHEME=https
export SYMFONY_PROJECT_DEFAULT_ROUTE_URL=https://127.0.0.1:8000/
export SYMFONY_TUNNEL=
export SYMFONY_TUNNEL_ENV=
```

and on Symfony Profiler has:
-  docker compose: down 
-  env vars: none

# My environment
- MacOS: Sonoma 14.0
- Docker Desktop: 4.24.0
- PHP: 8.1
- Symfony CLI: 5.5.10

# Solution (for me)
- In Docker-Settings / Advanced: "Allow the default Docker socket to be used (requires password)" has to be activated.

# Proposal
As this seems to be a common issue, it would maybe possible to add a check and hint in the Symfony CLI on:
- check:requirements
- book:check-requirments
- server:start

and on the PROFILER

**Comment by codedmonkey** [comment]
Thank you for directly posting the solution. I was getting very frustrated with the Symfony CLI because of this problem.

Aside from adding hints, it's very obvious to me the Symfony CLI is missing proper documentation. I'll try to see if I can do something about it.

**Comment by tucksaun** [comment]
Hi,

If `SYMFONY_DOCKER_ENV` is empty it means we didn't Docker is running. So I don't see how we could show a hint to the user to let them know Docker is not reachable. And Docker is not a requirement so we should not display a warning to every user not using it.

Therefore I believe https://github.com/symfony/symfony-docs/pull/19272 is the best course of action.

As is, I'm closing this one but anyone feel free to add a comment if someone knows how to detect this situation 🙂
