### ISSUE TITLE
Feature request : Adding Symfony Cli Command to create a new bundle structure, configuration and default composer.json

### ISSUE THREAD

**Issue by JFO-SNPS** [symfony-cli/symfony-cli#351]
Hello,

I've been using Symfony for almost three months now and I find the symfony cli 'new' command for creating projects really handy.

Developing within a team promoting code reuse, I have developed several bundles and recipes and I still find it tedious to have to create the bundles by hand.

I would really like to have a cli command to create new bundles with a basic file and directory structure and a basic composer.json pre-filled with the project name, a customizable basic psr4 and dependencies basic. This would greatly simplify my work.

(Translated with Google Translate ^^)

**Comment by fabpot** [comment]
It's out of the scope of this project. It might make sense in the Symfony Maker bundle project though. I encourage you to check there.

**Comment by JFO-SNPS** [comment]
In fact, it seems more logical to me that this is in symfony-cli, this avoids having to install symfony/console, symfony/maker-bundle and other dependencies. I create my bundle from scratches outside of any other symfony project.

So, each time I recreate my directory structure, my composer.json file with a type file and this could be automated via symfony-cli.
