### ISSUE TITLE
Can't update Symfony CLI

### ISSUE THREAD

**Issue by karaka200** [symfony-cli/symfony-cli#36]
Hi  
My Symfony CLI version is 5.0.8 and a few hours ago version 5.0.9 was released.  
Now I want update my Symfony CLI by using `symfony self-update` command but say there is no update:  
> Checking for Platform.sh CLI for Symfony updates (current version: 3.73.2)
No updates found  

@fabpot  What's wrong?

**Comment by fabpot** [comment]
Which package manager are you using?

**Comment by karaka200** [comment]
> Which package manager are you using?

Composer

**Comment by fabpot** [comment]
I can see now that you are using version 4 of the CLI, not version 5.
So, if you want to switch, remove the Symfony binary and install the version 5 one via one installation methods as described here: https://symfony.com/download

**Comment by karaka200** [comment]
Thank you,before I download from `https://github.com/symfony-cli/symfony-cli/releases/tag/v5.0.8` and extract.

**Comment by chapterjason** [comment]
@fabpot Can the ~/.symfony folder be removed? I just saw changes in the ~/.symfony5 folder and no updates in the old one after the update.

**Comment by fabpot** [comment]
@chapterjason Yes, it is safe to remove the ~/.symfony directory.

**Comment by karaka200** [comment]
@fabpot I install Symfony CLI in Windows via ` scoop install symfony-cli` but install Symfony v4.28.1 !

**Comment by fabpot** [comment]
@karaka200 It's not possible. Version 4 is not available via scoop. Have you removed version 4 first?

**Comment by karaka200** [comment]
@fabpot I uninstall completely Symfony CLi and then install again but install V4

**Comment by karaka200** [comment]
@fabpot When run `scoop install symfony-cli` then display this:

> Installing 'symfony-cli' (4.28.1) [64bit]
> symfony_windows_amd64.exe (18.1 MB) [>        ]   0%

**Comment by fabpot** [comment]
So, it looks someone has added version 4 to the Scoop repository: https://github.com/ScoopInstaller/Main/blob/master/bucket/symfony-cli.json
To be honest, I know nothing about Scoop.
If you run ` scoop bucket add symfony-cli https://github.com/symfony-cli/scoop-bucket.git` first, does it work better?

**Comment by karaka200** [comment]
No, unfortunately it does not matter

**Comment by karaka200** [comment]
`scoop` has problem. I install Symfony CLI with `GoFish` and it install Symfny CLI v5.0.9

**Comment by BahmanMD** [comment]
The problem was fixed.

**Comment by fabpot** [comment]
Thank you so much @BahmanMD. Does it mean that I can remove my scoop repository here https://github.com/symfony-cli/scoop-bucket?

Then, I suppose I need to also simplify the instructions on https://symfony.com/download to just `scoop install symfony-cli`, is that correct?

**Comment by BahmanMD** [comment]
@fabpot No, there is no need to remove https://github.com/symfony-cli/scoop-bucket repository.  
`scoop bucket add symfony-cli https://github.com/symfony-cli/scoop-bucket.git` command create a new bucket.  
When run `scoop search symfony-cli` command, displayed this message:  

> 'main' bucket:
>     symfony-cli (5.0.9)
> 
> 'symfony-cli' bucket:
>     symfony-cli (5.0.9)

So when you run `scoop install symfony-cli` command, install `symfony-cli` from `main` bucket.  
If you want to install `symfony-cli` from `symfony-cli` bucket, you must run `scoop install symfony-cli/symfony-cli`.

I did not find a place to edit https://symfony.com/download page, please edit it.

**Comment by fabpot** [comment]
But what's the point of having our own bucket if Symfony CLI is in the main Scoop repository?

**Comment by BahmanMD** [comment]
One of the reasons is the issue of updating that we can update faster in our bucket because it may take time to request an update to `main` bucket.

**Comment by fabpot** [comment]
All fixed now, thank you for your help @BahmanMD

**Comment by karaka200** [comment]
Hi

@fabpot When I use `symfony self-update` command, display this:

```
Checking for Platform.sh CLI for Symfony updates (current version: 3.74.0)
No updates found
```
but when use `scoop update symfony-cli` work fine and update Symfony CLI.

`symfony self-update` command no longer works?

**Comment by fabpot** [comment]
Correct, there is no `self-update` command anymore. What you are seeing here is the `cloud:self-update` command. I'm going to remove the shortcut to avoid confusion.
If you want a self-updating CLI, use one of the package managers we support.

**Comment by fabpot** [comment]
@karaka200 see #48

**Comment by Seb33300** [comment]
If we download the binary manually without using scoop, it is no more possible to self-update symfony cli?
We always  have to redownload the binary manually?

**Comment by lpokoradi** [comment]
@Seb33300: As Fabien stated above: Correct, there is no self-update command anymore. If you want a self-updating CLI, use one of the package managers we support.

I am maintaining the chocolatey packages of symfony-cli, in case you prefer that package manager. But that one is not officially supported by this project.

**Comment by Seb33300** [comment]
Sad. And [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/), the native windows package manager is not supported?

I dont really want to install another package manager just for this.

**Comment by Seb33300** [comment]
Someone already created a PR: https://github.com/microsoft/winget-pkgs/pull/455

**Comment by tucksaun** [comment]
Releasing on winget is hard to automate as Microsoft require a PR on each update.
Also, they only support installing apps without an installer as an experimental feature since recently.
Last the support is not added yet to goreleaser.

Regarding chocolatey, there's a pending PR here: #232.
Any help there is welcome

**Comment by tucksaun** [comment]
But while we wait for goreleaser to support winget, you can take-over https://github.com/microsoft/winget-pkgs/pull/455

**Comment by tucksaun** [comment]
> The self-update feature worked well on Windows [...]

Actually, it didn't work *that* well 😅
Over the several years when it was supported, we hit several issues with Windows that I never managed to get around.
Basically having a binary overwrite itself safely, without administrative privileges, and without being detected as some malware is not that easy 😢.

Now that the binary is open-source it means it's mostly volunteer work.
So on my side (speaking only for myself here!) I'm not inclined to support such a complicated feature on my personal time in the short future.
Especially since the move to package management means most platforms are not affected by those issues anymore.
