### ISSUE TITLE
[RFC] Command "server:close --all" / "server:close --port=XXXX"

### ISSUE THREAD

**Issue by smnandre** [symfony-cli/symfony-cli#367]
I frequently start multiple local servers and... forget to stop them. 

```
+---------------------------------------------+-------------+---------------------+
|                  Directory                  |    Port     |       Domains       |
+---------------------------------------------+-------------+---------------------+
| ~/Sites/example.com/api                     | Not running | api.example.wip     |
| ~/Sites/example.com/www                     | Not running | www.example.wip     |
| ~/dev/symfony/ux/ux.symfony.com             | 8001        |                     |
| ~/dev/symfony/demo                          | 8002        |                     |
| ~/Company/foo/project/in/a/really/deep/path | 8003        |                     |
| ~/Company/bar/project/in/another/deep/path  | 8004        |                     |
+---------------------------------------------+-------------+---------------------+
```

In that kind of situation I'd love to execute either

```
symfony server:close --all
```

or

```
server:close --port=8003
```

Would this be feasible? 

If no one has the time to do it... I could give it a try, but I never worked with GO. If there's any kind soul out there willing to guide me a bit, it would be much appreciated :)

**Comment by jannes-io** [comment]
Would love this. We used to run PHP docker containers before using symfony server, and we used to kill and remove all containers using a Makefile:
```
killenv:
	docker stop $$(docker ps -a -q) > /dev/null 2>&1 || true
	docker rm $$(docker ps -a -q) > /dev/null 2>&1 || true
```

But now with symfony server, we don't have a similar option. `symfony server:list` doesn't have a way to just only output the running directories, so we can't simply list all running directories and stop them.

Workarounds exist with checking PIDs of programs using a certain port and killing them, but that's not a very clean solution...

Adding a stop all function like this issue suggests, or some flags to `server:list` to only output directories would help greatly for people who run a lot of different projects.

**Comment by tucksaun** [comment]
@smnandre yeah this is feasible and we should have all the primitive required, some code factoring from `server:stop` might be nice though.

**Comment by tucksaun** [comment]
but exposing a `port` flag does not seem idiomatic with the experience we want to expose in the CLI: using `server:stop` with the `--directory` flag seems more in-par with the overall experience

**Comment by tucksaun** [comment]
> Would love this. We used to run PHP docker containers before using symfony server, and we used to kill and remove all containers using a Makefile:
> 
> ```
> killenv:
> 	docker stop $$(docker ps -a -q) > /dev/null 2>&1 || true
> 	docker rm $$(docker ps -a -q) > /dev/null 2>&1 || true
> ```
> 
> But now with symfony server, we don't have a similar option. `symfony server:list` doesn't have a way to just only output the running directories, so we can't simply list all running directories and stop them.
> 
> Workarounds exist with checking PIDs of programs using a certain port and killing them, but that's not a very clean solution...
> 
> Adding a stop all function like this issue suggests, or some flags to `server:list` to only output directories would help greatly for people who run a lot of different projects.

@jannes-io I have the sense that only running `server:stop` would meet your requirement, or did I misunderstand your use case?  🤔

**Comment by jannes-io** [comment]
> @jannes-io I have the sense that only running `server:stop` would meet your requirement, or did I misunderstand your use case? 🤔

Long story short, yes. Just providing a real-world use case 😆

**Comment by smnandre** [comment]
@tucksaun ok i'll give it a try ... if you had to give me one advice before i start ~coding~ moving code in GO, what would it be ? :)

**Comment by alexandre-daubois** [comment]
Hi @smnandre, still up for a PR or can I give it a try? 🙂

**Comment by smnandre** [comment]
@alexandre-daubois oh please do :))
