### ISSUE TITLE
The new version is not installed

### ISSUE THREAD

**Issue by nvrsk-yii2** [symfony-cli/symfony-cli#37]
When installing according to the instructions:
`scoop bucket add symfony-cli https://github.com/symfony-cli/scoop-bucket.git`
`scoop install symfony-cli`
Installed 4.28.1

**Comment by fabpot** [comment]
It is installed for sure as scoop knows nothing about version 4. It means that v4 is in your PATH, before v5. Rename or remove the v4 binary and this will fix the problem.

**Comment by nvrsk-yii2** [comment]
I installed a clean system. 
I had to delete scoop bucket main
Then delete symfony-cli
Clear cache 
After that, everything was established correctly.
