### ISSUE TITLE
messenger:consume async should wait for Docker compose services to be up

### ISSUE THREAD

**Issue by jmsche** [symfony-cli/symfony-cli#374]
Using Symfony CLI 5.7.0 which adds `docker_compose` support.

In `compose.yaml` there is only a RabbitMQ image declared. I've tried adding several health checks,
but none seems to work.

In `.symfony.local.yaml` two workers are declared:

- docker_compose
- messenger_consume_async

I guess the messenger:consume command starts before RabbitMQ is completely up.

## How to reproduce

```shell
git clone https://github.com/jmsche/symfony-cli-rabbitmq-async-reproducer.git
cd symfony-cli-rabbitmq-async-reproducer
composer install
symfony serve
```

## Logs

Important part:

```
WARNING Worker "messenger_consume_async" exited with an error: command "symfony console messenger:consume async" failed early: exit status 1
```

<details>
<summary>Click to see logs</summary>

Following Web Server log file (/home/jmsche/.symfony5/log/c8e62a91ef0ea289fe06cb29f90e9dbd7e4a2a8a.log)
Following PHP-FPM log file (/home/jmsche/.symfony5/log/c8e62a91ef0ea289fe06cb29f90e9dbd7e4a2a8a/53fb8ec204547646acb3461995e4da5a54cc7575.log)

[WARNING] The local web server is optimized for local development and MUST never be used in a production setup.

[OK] Web server listening                                                                                              
The Web server is using PHP FPM 8.2.12                                                                            
https://127.0.0.1:8000

INFO Worker "messenger_consume_async" waiting for Docker Compose to be up
[Web Server ] Nov  6 09:16:42 |DEBUG  | PHP    Reloading PHP versions
[Web Server ] Nov  6 09:16:42 |DEBUG  | PHP    Using PHP version 8.2.12 (from default version in $PATH)

[OK] Started worker "docker_compose"

[Web Server ] Nov  6 09:16:42 |INFO   | PHP    listening path="/usr/sbin/php-fpm8.2" php="8.2.12" port=39743
[PHP-FPM    ] Nov  6 09:16:42 |NOTICE | FPM    fpm is running, pid 51527
[PHP-FPM    ] Nov  6 09:16:42 |NOTICE | FPM    ready to handle connections
[PHP-FPM    ] Nov  6 09:16:42 |NOTICE | FPM    systemd monitor interval set to 10000ms
INFO Docker Compose is now up, switching to non detached mode
{"level":"error","time":"2023-11-06T09:16:44+01:00","message":"command \"docker compose up\" exited, restarting it immediately"}

[OK] Started worker "messenger_consume_async"

Following docker compose up log file (/home/jmsche/.symfony5/log/c8e62a91ef0ea289fe06cb29f90e9dbd7e4a2a8a/145c99629866f40e4a3017532ef0ad5961f70677.log)
WARNING Worker "messenger_consume_async" exited with an error: command "symfony console messenger:consume async" failed early: exit status 1
[Worker docker]  Container symfony-cli-rabbitmq-async-rabbitmq-1  Running
[Worker docker] Attaching to symfony-cli-rabbitmq-async-rabbitmq-1
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.094907+00:00 [notice] <0.44.0> Application syslog exited with reason: stopped
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.096840+00:00 [notice] <0.230.0> Logging: switching to configured handler(s); following messages may not be visible in this log output
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.097201+00:00 [notice] <0.230.0> Logging: configured log handlers are now ACTIVE
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.224162+00:00 [info] <0.230.0> ra: starting system quorum_queues
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.224228+00:00 [info] <0.230.0> starting Ra system: quorum_queues in directory: /var/lib/rabbitmq/mnesia/rabbit@3e351f267957/quorum/rabbit@3e351f267957
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.231192+00:00 [info] <0.316.0> ra system 'quorum_queues' running pre init for 0 registered servers
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.234695+00:00 [info] <0.317.0> ra: meta data store initialised for system quorum_queues. 0 record(s) recovered
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.239461+00:00 [notice] <0.322.0> WAL: ra_log_wal init, open tbls: ra_log_open_mem_tables, closed tbls: ra_log_closed_mem_tables
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.246612+00:00 [info] <0.230.0> ra: starting system coordination
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.246647+00:00 [info] <0.230.0> starting Ra system: coordination in directory: /var/lib/rabbitmq/mnesia/rabbit@3e351f267957/coordination/rabbit@3e351f267957
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.246989+00:00 [info] <0.329.0> ra system 'coordination' running pre init for 0 registered servers
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.247261+00:00 [info] <0.330.0> ra: meta data store initialised for system coordination. 0 record(s) recovered
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.247332+00:00 [notice] <0.335.0> WAL: ra_coordination_log_wal init, open tbls: ra_coordination_log_open_mem_tables, closed tbls: ra_coordination_log_closed_mem_tables
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.253331+00:00 [info] <0.230.0>
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.253331+00:00 [info] <0.230.0>  Starting RabbitMQ 3.12.7 on Erlang 25.3.2.7 [jit]
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.253331+00:00 [info] <0.230.0>  Copyright (c) 2007-2023 VMware, Inc. or its affiliates.
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.253331+00:00 [info] <0.230.0>  Licensed under the MPL 2.0. Website: https://rabbitmq.com
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   ##  ##      RabbitMQ 3.12.7
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   ##  ##
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   ##########  Copyright (c) 2007-2023 VMware, Inc. or its affiliates.
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   ######  ##
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   ##########  Licensed under the MPL 2.0. Website: https://rabbitmq.com
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   Erlang:      25.3.2.7 [jit]
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   TLS Library: OpenSSL - OpenSSL 3.1.4 24 Oct 2023
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   Release series support status: supported
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   Doc guides:  https://rabbitmq.com/documentation.html
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   Support:     https://rabbitmq.com/contact.html
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   Tutorials:   https://rabbitmq.com/getstarted.html
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   Monitoring:  https://rabbitmq.com/monitoring.html
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   Logs: <stdout>
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   Config file(s): /etc/rabbitmq/conf.d/10-defaults.conf
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |   Starting broker...2023-11-06 08:16:46.257200+00:00 [info] <0.230.0>
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.257200+00:00 [info] <0.230.0>  node           : rabbit@3e351f267957
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.257200+00:00 [info] <0.230.0>  home dir       : /var/lib/rabbitmq
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.257200+00:00 [info] <0.230.0>  config file(s) : /etc/rabbitmq/conf.d/10-defaults.conf
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.257200+00:00 [info] <0.230.0>  cookie hash    : AUM8oCPehMZIQyif7Lcyxg==
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.257200+00:00 [info] <0.230.0>  log(s)         : <stdout>
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:46.257200+00:00 [info] <0.230.0>  data dir       : /var/lib/rabbitmq/mnesia/rabbit@3e351f267957
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.377640+00:00 [info] <0.230.0> Running boot step pre_boot defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.377703+00:00 [info] <0.230.0> Running boot step rabbit_global_counters defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.377971+00:00 [info] <0.230.0> Running boot step rabbit_osiris_metrics defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.378032+00:00 [info] <0.230.0> Running boot step rabbit_core_metrics defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.378578+00:00 [info] <0.230.0> Running boot step rabbit_alarm defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.381289+00:00 [info] <0.354.0> Memory high watermark set to 12703 MiB (13320357478 bytes) of 31758 MiB (33300893696 bytes) total
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.383405+00:00 [info] <0.356.0> Enabling free disk space monitoring (disk free space: 437565034496, total memory: 33300893696)
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.383433+00:00 [info] <0.356.0> Disk free limit set to 50MB
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.384167+00:00 [info] <0.230.0> Running boot step code_server_cache defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.384211+00:00 [info] <0.230.0> Running boot step file_handle_cache defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.384327+00:00 [info] <0.359.0> Limiting to approx 1048479 file handles (943629 sockets)
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.384386+00:00 [info] <0.360.0> FHC read buffering: OFF
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.384469+00:00 [info] <0.360.0> FHC write buffering: ON
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.384798+00:00 [info] <0.230.0> Running boot step worker_pool defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.384848+00:00 [info] <0.337.0> Will use 16 processes for default worker pool
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.384871+00:00 [info] <0.337.0> Starting worker pool 'worker_pool' with 16 processes in it
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.385199+00:00 [info] <0.230.0> Running boot step database defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.385867+00:00 [info] <0.230.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.399198+00:00 [info] <0.230.0> Successfully synced tables from a peer
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415037+00:00 [info] <0.230.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415104+00:00 [info] <0.230.0> Successfully synced tables from a peer
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415123+00:00 [info] <0.230.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping registration.
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415250+00:00 [info] <0.230.0> Running boot step tracking_metadata_store defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415323+00:00 [info] <0.386.0> Setting up a table for connection tracking on this node: tracked_connection
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415374+00:00 [info] <0.386.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415450+00:00 [info] <0.386.0> Setting up a table for per-user connection counting on this node: tracked_connection_per_user
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415488+00:00 [info] <0.386.0> Setting up a table for channel tracking on this node: tracked_channel
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415535+00:00 [info] <0.386.0> Setting up a table for channel tracking on this node: tracked_channel_per_user
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415567+00:00 [info] <0.230.0> Running boot step networking_metadata_store defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415613+00:00 [info] <0.230.0> Running boot step feature_flags defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415702+00:00 [info] <0.230.0> Running boot step codec_correctness_check defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415737+00:00 [info] <0.230.0> Running boot step external_infrastructure defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415748+00:00 [info] <0.230.0> Running boot step rabbit_event defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415818+00:00 [info] <0.230.0> Running boot step rabbit_registry defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415859+00:00 [info] <0.230.0> Running boot step rabbit_auth_mechanism_amqplain defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415925+00:00 [info] <0.230.0> Running boot step rabbit_auth_mechanism_cr_demo defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.415967+00:00 [info] <0.230.0> Running boot step rabbit_auth_mechanism_plain defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416015+00:00 [info] <0.230.0> Running boot step rabbit_exchange_type_direct defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416050+00:00 [info] <0.230.0> Running boot step rabbit_exchange_type_fanout defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416080+00:00 [info] <0.230.0> Running boot step rabbit_exchange_type_headers defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416120+00:00 [info] <0.230.0> Running boot step rabbit_exchange_type_topic defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416150+00:00 [info] <0.230.0> Running boot step rabbit_mirror_queue_mode_all defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416176+00:00 [info] <0.230.0> Running boot step rabbit_mirror_queue_mode_exactly defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416226+00:00 [info] <0.230.0> Running boot step rabbit_mirror_queue_mode_nodes defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416261+00:00 [info] <0.230.0> Running boot step rabbit_priority_queue defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416300+00:00 [info] <0.230.0> Priority queues enabled, real BQ is rabbit_variable_queue
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416341+00:00 [info] <0.230.0> Running boot step rabbit_queue_location_client_local defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416387+00:00 [info] <0.230.0> Running boot step rabbit_queue_location_min_masters defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416445+00:00 [info] <0.230.0> Running boot step rabbit_queue_location_random defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416479+00:00 [info] <0.230.0> Running boot step kernel_ready defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416492+00:00 [info] <0.230.0> Running boot step rabbit_sysmon_minder defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416579+00:00 [info] <0.230.0> Running boot step rabbit_epmd_monitor defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416883+00:00 [info] <0.394.0> epmd monitor knows us, inter-node communication (distribution) port: 25672
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.416937+00:00 [info] <0.230.0> Running boot step guid_generator defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.422324+00:00 [info] <0.230.0> Running boot step rabbit_node_monitor defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.422439+00:00 [info] <0.398.0> Starting rabbit_node_monitor (in ignore mode)
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.422645+00:00 [info] <0.230.0> Running boot step delegate_sup defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.422914+00:00 [info] <0.230.0> Running boot step rabbit_memory_monitor defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423029+00:00 [info] <0.230.0> Running boot step rabbit_fifo_dlx_sup defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423061+00:00 [info] <0.230.0> Running boot step core_initialized defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423074+00:00 [info] <0.230.0> Running boot step rabbit_channel_tracking_handler defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423135+00:00 [info] <0.230.0> Running boot step rabbit_connection_tracking_handler defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423159+00:00 [info] <0.230.0> Running boot step rabbit_definitions_hashing defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423187+00:00 [info] <0.230.0> Running boot step rabbit_exchange_parameters defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423323+00:00 [info] <0.230.0> Running boot step rabbit_mirror_queue_misc defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423518+00:00 [info] <0.230.0> Running boot step rabbit_policies defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423710+00:00 [info] <0.230.0> Running boot step rabbit_policy defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423735+00:00 [info] <0.230.0> Running boot step rabbit_queue_location_validator defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423768+00:00 [info] <0.230.0> Running boot step rabbit_quorum_memory_manager defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423807+00:00 [info] <0.230.0> Running boot step rabbit_stream_coordinator defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423883+00:00 [info] <0.230.0> Running boot step rabbit_vhost_limit defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423930+00:00 [info] <0.230.0> Running boot step rabbit_mgmt_reset_handler defined by app rabbitmq_management
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423954+00:00 [info] <0.230.0> Running boot step rabbit_mgmt_db_handler defined by app rabbitmq_management_agent
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.423981+00:00 [info] <0.230.0> Management plugin: using rates mode 'basic'
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.424099+00:00 [info] <0.230.0> Running boot step recovery defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.424517+00:00 [info] <0.434.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@3e351f267957/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L' for vhost '/' exists
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.430605+00:00 [info] <0.434.0> Starting message stores for vhost '/'
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.430735+00:00 [info] <0.444.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_transient": using rabbit_msg_store_ets_index to provide index
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.431302+00:00 [info] <0.434.0> Started message store of type transient for vhost '/'
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.431387+00:00 [info] <0.448.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.431734+00:00 [warning] <0.448.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent" : failed to read recovery terms: enoent
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.431734+00:00 [warning] <0.448.0> rebuilding indices from scratch
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.432142+00:00 [info] <0.434.0> Started message store of type persistent for vhost '/'
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.432212+00:00 [info] <0.434.0> Recovering 0 queues of type rabbit_classic_queue took 7ms
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.432240+00:00 [info] <0.434.0> Recovering 0 queues of type rabbit_quorum_queue took 0ms
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.432278+00:00 [info] <0.434.0> Recovering 0 queues of type rabbit_stream_queue took 0ms
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.433078+00:00 [info] <0.230.0> Running boot step empty_db_check defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.433109+00:00 [info] <0.230.0> Will not seed default virtual host and user: have definitions to load...
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.433149+00:00 [info] <0.230.0> Running boot step rabbit_observer_cli defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.433192+00:00 [info] <0.230.0> Running boot step rabbit_looking_glass defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.433220+00:00 [info] <0.230.0> Running boot step rabbit_core_metrics_gc defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.433357+00:00 [info] <0.230.0> Running boot step background_gc defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.433425+00:00 [info] <0.230.0> Running boot step routing_ready defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.433464+00:00 [info] <0.230.0> Running boot step pre_flight defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.433505+00:00 [info] <0.230.0> Running boot step notify_cluster defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.433535+00:00 [info] <0.230.0> Running boot step networking defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.433552+00:00 [info] <0.230.0> Running boot step definition_import_worker_pool defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.433593+00:00 [info] <0.337.0> Starting worker pool 'definition_import_pool' with 16 processes in it
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.434039+00:00 [info] <0.230.0> Running boot step cluster_name defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.434071+00:00 [info] <0.230.0> Running boot step direct_client defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.434137+00:00 [info] <0.230.0> Running boot step rabbit_maintenance_mode_state defined by app rabbit
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.434214+00:00 [info] <0.230.0> Creating table rabbit_node_maintenance_states for maintenance mode status
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.434367+00:00 [info] <0.230.0> Running boot step rabbit_management_load_definitions defined by app rabbitmq_management
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.434434+00:00 [info] <0.499.0> Resetting node maintenance status
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.442549+00:00 [info] <0.558.0> Management plugin: HTTP (non-TLS) listener started on port 15672
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.442637+00:00 [info] <0.586.0> Statistics database started.
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.442683+00:00 [info] <0.585.0> Starting worker pool 'management_worker_pool' with 3 processes in it
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.446869+00:00 [info] <0.600.0> Prometheus metrics: HTTP (non-TLS) listener started on port 15692
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.446931+00:00 [info] <0.499.0> Ready to start client connection listeners
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.447555+00:00 [info] <0.644.0> started TCP listener on [::]:5672
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  |  completed with 4 plugins.
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.475678+00:00 [info] <0.499.0> Server startup complete; 4 plugins started.
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.475678+00:00 [info] <0.499.0>  * rabbitmq_prometheus
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.475678+00:00 [info] <0.499.0>  * rabbitmq_management
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.475678+00:00 [info] <0.499.0>  * rabbitmq_management_agent
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.475678+00:00 [info] <0.499.0>  * rabbitmq_web_dispatch
[Worker docker] symfony-cli-rabbitmq-async-rabbitmq-1  | 2023-11-06 08:16:47.635503+00:00 [info] <0.9.0> Time to start RabbitMQ: 2568311 us
</details>

**Comment by tucksaun** [comment]
OK so I believed `docker compose` would wait for the services to be ready in such case but in fact you would need to use `--wait`.

the problem is that `--wait` will return with a failure exit code if only a single service has non `healthcheck` defined...

currently trying to find an acceptable solution to work around this...

**Comment by tucksaun** [comment]
> the problem is that --wait will return with a failure exit code if only a single service has non healthcheck defined...

Actually, I was wrong and this looks to be specific to my project (and/or a bug in docker-compose)
