### ISSUE TITLE
symfony-cli: web-server and/or fpm lost the "host" context

### ISSUE THREAD

**Issue by smnandre** [symfony-cli/symfony-cli#382]
Update: almost there.

### Bug / how 

- on Firefox with symfony-cli, any "Link preload" make the network crash 
- the bug comes from the fact the "host" context seems to be lost during the exchanges... See last comment.
- after investiagations / repro Symfony PHP code is not in cause at all (see the micro following reproducer)
- some request are handle on a given port (by web server), some on another one (php), making HTTP2 .. unstable
- there is a [hard-coded port 8004](https://github.com/symfony-cli/symfony-cli/blob/14c33913686ab0f026cdc1c7e0e62cea48dd09ed/local/http/http.go#L206) here that Firefox does not like 
- it's not a recent change, but that may be have been "triggered" A) by new features in FF allowing some header Links B) recent symfony-cli changes concerning cgi / env vars

### Temporary solution

On a Symfony app, the simple solution is to disable weblink in dev environment.

```yaml
# config/framework.yaml

framework:
    # ...
   
    web_link: false
```    

For the most basic needs (render a CSS) it's enough to get back a enjoyable DX in dev.

⚠️  it only works if you don't  manually set Link headers in your code, as it prevent the registration of the  [AddLinkHeaderListener](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/WebLink/EventListener/AddLinkHeaderListener.php). 

You may want to chose another value (not debug ?), or to enable it just in prod...

---

### MicroReproducer

<details>
<summary>
`/index.php`
</summary>

```php
<?php header('Link: </foo.css>; rel=preload; as="style"; type="text/css"'); ?>
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<link rel="stylesheet" href="/foo.css" type="text/css" />
		<title>Test</title>
	</head>
	<body>
		<h1>Test preload header</h1>
	</body>
</html>	
```
</details>

<details>
<summary>
`/foo.css`
</summary>

```css
h1 {
	color: green;
}
```

</details>

Then run `symfony serve`. The web page is dsplayed on all major browsers. 

🥶  But if you refresh once or twice quickyl, with Firefox you're entirely stuck.

... 

--- 

ORIGINAL POST:

I finally found what creates my "[everything is frozen](https://github.com/symfony-cli/symfony-cli/issues/381#issuecomment-1817680173)" situation.

## What

Firefox and/or Symfony local server is stuck after interrupted request with [resource hints](https://symfony.com/doc/current/web_link.html#how-does-it-work).

## When 

When i use the symfony local server, a refresh (or anything that cut/cancel ongoing requests) with resource Preloads make the entire tab stucked.

It happens for me on the [ux website](https://github.com/symfony/ux/tree/2.x/ux.symfony.com). But as soon i uninstall symfony/web-link everythings normal again.

## Why

(AssetMapper [sends resource hints](https://github.com/symfony/symfony/blob/37f04cf0ac3fb08ee1ab4a2c1241ec6a926bc696/src/Symfony/Component/AssetMapper/ImportMap/ImportMapRenderer.php#L170) when the web-link component is installed) 

So not sure if this is a 
- firefox-only bug
- asset-mapper-only bug
- symfony-cli-only bug

... or a bit of all :| 

What do you think ? What could i do to continue the investigation ?

**Comment by smnandre** [comment]
Update: there is a bug in WebLink ... gonna fix it and check back if everything works here

**Comment by smnandre** [comment]
So after an epic investigation, here are my conclusions:
- AssetMapper va only guilty of multiplying the requests, clearly not helping but not responsible at core
- Firefox seems to have a problem with preload link header and root-relative URI 
- No problem with Safari/Chrome

But... Firefox has no problem on multiple online sites i tested online...

... and on multiple occasions i found strange things in the server log.

So either it's a firefox-only bug.... or the symfony-cli proxy / certificates have a weird hard-to-reproduce bug....
... or maybe i messed totally with my local.


So if anyone want to check on its browser, that could be a great help ❤️ 

I put the reproducer here with instructions... and i'll try to upload the video if Github allows it

https://github.com/smnandre/firefox-preload-link

**Comment by smnandre** [comment]
Update: 

So there is a problem, and it really is related to the symfony-cli... or me (but nothing with Symfony framework) 

i made a minimal repro without Symfony (app) and just symfony-cli.

When the webserver listen on port 8001 or 8007, the php-fpm lose the context, host, and listen on the on 8004 apparently 🤯 


<img width="2538" alt="tests" src="https://github.com/symfony-cli/symfony-cli/assets/1359581/6eebfb0e-21e5-4958-b3bb-d705b45588e2">



```
[Web Server ] Nov 25 21:44:34 |DEBUG  | PHP    Reloading PHP versions
[Web Server ] Nov 25 21:44:34 |DEBUG  | PHP    Using PHP version 8.2.12 (from default version in $PATH)
[Web Server ] Nov 25 21:44:34 |INFO   | PHP    listening path="/opt/homebrew/Cellar/php/8.2.12_1/sbin/php-fpm" php="8.2.12" port=58041
[PHP-FPM    ] Nov 25 21:44:34 |NOTICE | FPM    fpm is running, pid 53119
[PHP-FPM    ] Nov 25 21:44:34 |NOTICE | FPM    ready to handle connections
[Web Server ] Nov 25 21:45:07 |INFO   | SERVER GET  (200) / ip="127.0.0.1" preloaded_resources=["/foo.css"]
[Web Server ] Nov 25 21:45:07 |INFO   | SERVER GET  (200) /foo.css
[Web Server ] Nov 25 21:45:07 |INFO   | SERVER GET  (200) /foo.css
[Web Server ] Nov 25 21:45:07 |INFO   | SERVER GET  (200) /bar.css
[Web Server ] Nov 25 21:45:07 |INFO   | SERVER GET  (200) /favicon.ico
[Web Server ] Nov 25 21:45:08 |INFO   | SERVER GET  (200) / preloaded_resources=["/foo.css"]
[Web Server ] Nov 25 21:45:08 |INFO   | SERVER GET  (200) /foo.css
```


---

<details>
<summary>
⏬   symfony serve
</summary>

```
 [WARNING] The local web server is optimized for local development and MUST never be used in a production setup.

 [OK] Web server listening
      The Web server is using PHP FPM 8.2.12
      https://127.0.0.1:8007


Stream the logs via symfony server:log
```
</details>

<details>
<summary>
⏬   .symfony5/log/8145f43d881fa847dba2897e6e471416caf77c74.log 
</summary>

```
➜  preload-header tail /Users/simonandre/.symfony5/log/8145f43d881fa847dba2897e6e471416caf77c74.log
{"level":"debug","source":"server","source":"PHP","time":"2023-11-25T21:50:18+01:00","message":"Reloading PHP versions"}
{"level":"debug","source":"server","source":"PHP","time":"2023-11-25T21:50:18+01:00","message":"Using PHP version 8.2.12 (from default version in $PATH)"}
{"level":"info","source":"server","source":"PHP","php":"8.2.12","path":"/opt/homebrew/Cellar/php/8.2.12_1/sbin/php-fpm","port":58108,"time":"2023-11-25T21:50:18+01:00","message":"listening"}
{"level":"info","source":"server","ip":"127.0.0.1","status":200,"method":"GET","scheme":"https","host":"127.0.0.1:8004","preloaded_resources":["/foo.css"],"time":"2023-11-25T21:50:23+01:00","message":"/"}
{"level":"info","source":"server","ip":"127.0.0.1","status":200,"method":"GET","scheme":"https","host":"127.0.0.1:8004","time":"2023-11-25T21:50:23+01:00","message":"/foo.css"}
```
</details>


I rebooted, i exited all php running processes, I started/stopped Symfony proxy server, etc etc

I tried with without .symfony.local.yaml file
```
http:
    port: 8007 # Force the port that will be used to run the server
```

So... before i reinstall all my OS, is there anything i could try with the symfony-cli ?  🙏

**Comment by smnandre** [comment]
Post updated to present the temporary solution, until a solution is found (either in config, sf-cli or .... Firefox)

**Comment by fabpot** [comment]
@smnandre Can you confirm that #391 fixes your issue?

**Comment by smnandre** [comment]
It's perfect now i'm sorry i missed those messages. Thank you very much !
