### ISSUE TITLE
Further elaboration about web server in productive use is necessary

### ISSUE THREAD

**Issue by frederik-b** [symfony-cli/symfony-cli#39]
Hi,

I would like to know why the server is not intended for production usage.
(Stated here: https://symfony.com/doc/current/setup/symfony_server.html)

Is it just not intended, but totally fine to do so, or are there definite reasons,
why it is not safe to do so or maybe just performance?

For low volume services that are not exactly performance critical it is often times
less complex to run a single app container instead of running a set.
Although running it with caddy looks simple enough (e.g. https://github.com/dunglas/symfony-docker/blob/main/docker-compose.prod.yml).

Which means I don't necessarily have to run the symfony server in productive use,
but I would need any information why it is not intended and what's exactly meant by this
to form an educated conclusion whether it is fit for my intended scenario.
And I can't do this based on the given information.

And I think this is a general issue with this project, not simply my situation with it.

**Comment by fabpot** [comment]
Quick answer: it is not designed for production: it's not optimized to serve pages fast, it's not secured, and more generally, it's optimized for debugging.
As you said, using Caddy is the way to go if you want something simple that comes as a single binary.
