### ISSUE TITLE
Command server:stop doesn't stop docker_compose worker if server was started with --deamon

### ISSUE THREAD

**Issue by yguedidi** [symfony-cli/symfony-cli#390]
To reproduce

- have in `.symfony.local.yaml`
    ```yaml
    workers:
        docker_compose: ~
    ```
- run `symfony server:start --daemon`
- run `docker compose ps` to see containers running
- run `symfony server:stop`
- run `docker compose ps` again to see containers still running

is this an expected behavior?

**Comment by tucksaun** [comment]
definitely not the expected behavior. will try to have a look
