### ISSUE TITLE
Time out detected during "Worker docker" process exit

### ISSUE THREAD

**Issue by yguedidi** [symfony-cli/symfony-cli#398]
Since #390 stopping docker compose works like a charm when ran in daemon mode (first `server:start --daemon` then `server:stop`!
But it seems it broke the non daemon mode (just `server:start` then Ctrl+C)...

After I hit Ctrl+C, I get this
![image](https://github.com/symfony-cli/symfony-cli/assets/1480128/3ff3c11b-4c57-4146-95f6-1ce51a7f34d4)

**Comment by yguedidi** [comment]
Seems not fixed with latest version 5.8.1

**Comment by zulus** [comment]
Also #402 come back again in 5.8.1. Probably because SIGINT is not forwarded: https://github.com/symfony-cli/symfony-cli/commit/ff1958fbb1f875372c8d654e37f4c7c29327e9f2

**Comment by zulus** [comment]
https://github.com/docker/for-mac/issues/7150

**Comment by yguedidi** [comment]
Closing as on 5.8.14 it seems to be fixed
