### ISSUE TITLE
Inappropriate ioctl for device in CI since 5.8.0

### ISSUE THREAD

**Issue by tgalopin** [symfony-cli/symfony-cli#409]
Hi guys!

Since 5.8.0, we experience an issue with seems related to Symfony CLI upgrade:

```
command "vendor/bin/codecept run --no-interaction" failed to start: fork/exec vendor/bin/codecept: inappropriate ioctl for device
```

I tried adding --no-interation, without success:

```
symfony --no-interaction run vendor/bin/codecept run --no-interaction 
```

**Comment by sarim** [comment]
> Hi @sarim ! I think maybe https://github.com/symfony-cli/symfony-cli/issues/409 is related to this, maybe we should also use the interactivity detection (flag/terminal) when populating the Foreground argument?

_Originally posted by @tgalopin in https://github.com/symfony-cli/symfony-cli/issues/405#issuecomment-1883371440_


@tgalopin Is it very much possible that PR broke this case. I used the variables/information already present in buildCmd function to make the isForeground decision. I'm looking into it.

**Comment by tgalopin** [comment]
It's in a CI pipeline on GitHub Action, on Ubuntu latest using shivammathur/setup-php@v2

I'll see if I can replicate easily in a dedicated repo

**Comment by sarim** [comment]
@tgalopin Yeah I guess thats the problem. I can't reproduce it in my ubuntu (WSL2) terminal. In CI pipeline there is no tty/terminal associated so that causes the issue.

**Comment by tgalopin** [comment]
Here is a reproducer:

https://github.com/tgalopin/symfony-cli-reproducer/actions/runs/7464176264/job/20310551888
https://github.com/tgalopin/symfony-cli-reproducer/blob/main/.github/workflows/ci.yaml

**Comment by sarim** [comment]
@tgalopin I pushed a quick fix. https://github.com/sarim/symfony-cli/commit/2058b9452305dd0bb1eeec4073bd60013093b8d3

I also updated forked and updated your reproducer repo with symfony-cli binary from my commit. Here : https://github.com/sarim/symfony-cli-reproducer/commit/2d84631a70bce7639857806979ac167e11d0ee63

Can you confirm if that solves your issue? Then I'll open a PR here.

**Comment by tgalopin** [comment]
It works! Thanks :)
