### ISSUE TITLE
Windows antivirus detection (Norton)

### ISSUE THREAD

**Issue by Shadow-Devil** [symfony-cli/symfony-cli#414]
I just tried to install the Windows 386 binary but my antivirus program [Norton](https://us.norton.com)
immediately removed it since was detected as "WS.Reputation.1".

Details:
File name: symfony.exe
Threat name: WS.Reputation.1
Full path: C:\Users\fschn\.symfony-cli\symfony.exe

____________________________

On computers from 
18.01.2024 at 20:59:50

Last used 
18.01.2024 at 21:01:50

Start object 
No
Started 
No
Type of threat: Insight network threat. There are several indications that this file is untrusted and therefore unsafe

____________________________

symfony.exe Threat name: WS.Reputation.1
Search

Very few users
Less than 5 users in the Norton community have used this file.

Very recent
This file was released less than 1 week ago.

Medium
The risk of this file is medium.

____________________________

Source: External data carrier

Source file: 
symfony.exe

____________________________

File actions

File: C:\Users\fschn\.symfony-cli\symfony.exe removed

____________________________

File impression - SHA:
3ae7b9c9fb8db9cb2ff2170612fddf62ece14a1f8aae060b684220638f23c96f
File impression - MD5:
ddbc2c19463180ac0727353d0b567349

**Comment by fabpot** [comment]
I suppose there is nothing we can do here.
Thanks for reporting.

**Comment by tucksaun** [comment]
If I understand correctly, Norton determines the binary is untrustworthy because it is recent and not quite used among the Norton users community but it did not detect any virus signature.
So there's nothing we can do but you can let Norton know this binary is trustworthy.
