### ISSUE TITLE
PATCH requests over HTTP with local server not possible

### ISSUE THREAD

**Issue by nussjustin-hmmh** [symfony-cli/symfony-cli#428]
The github.com/soheilhy/cmux package used to handle both HTTP and HTTPS requests on the same port does not support the PATCH method.

Sending a PATCH method over HTTP will result in the request being treated as HTTPS and failing hard.

An example output when using `curl`:

```
> PATCH / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/8.2.1
> Content-Type: application/json
> Accept: application/json
> Content-Length: 120
> 
* Recv failure: Connection reset by peer
* Closing connection
curl: (56) Recv failure: Connection reset by peer

```

There is already an open issue about this in the cmux repository (soheilhy/cmux#99) but considering that the package has not been updated in 3 years it seems unlikely that the issue will be fixed there.

A possible solution would be to create a fork of the cmux package and add support for PATCH there.

I also looked for other similar packages but couldn't find one.

**Comment by tucksaun** [comment]
hi @nussjustin-hmmh 

thank you for the report 

it looks like we can simply add PATCH to the allowed method list for `HTTP1Fast`, see #429 for a fix
