### ISSUE TITLE
Toolbar code violates Content-Security-Policy

### ISSUE THREAD

**Issue by leofeyer** [symfony-cli/symfony-cli#446]
There are three inline `style` attributes in the toolbar source code, which violate Content-Security-Policy:

https://github.com/symfony-cli/symfony-cli/blob/848f679253b28e03b8563fc252d7a2fdcc9eee54/local/php/toolbar.go#L164-L165

https://github.com/symfony-cli/symfony-cli/blob/848f679253b28e03b8563fc252d7a2fdcc9eee54/local/php/toolbar.go#L170

<img width="1163" alt="" src="https://github.com/symfony-cli/symfony-cli/assets/1192057/43164b95-a33e-47af-bf42-6b44872b145e">

This is because `unsafe-inline` is ignored if either a hash or nonce value is present in the source list, which is the case in the Symfony profiler.

**Comment by tucksaun** [comment]
Thank you for reporting the issue. it should be fixed with #450

**Comment by leofeyer** [comment]
Nice. 🎉 Thank you.
