### ISSUE TITLE
Re-add `check:security` command?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony-cli/symfony-cli#45]
As Fabien said [here](https://github.com/symfony-cli/symfony-cli/issues/9#issuecomment-1003554277):

> The (check:security) command does not exist in the new version of the CLI, you should use https://github.com/fabpot/local-php-security-checker instead.

Unless there are technical reasons to not do it, could we please reconsider adding the command again? It was very useful and the alternative of having to install another project to have that feature causes lots of friction in my opinion.

Thanks!

**Comment by stof** [comment]
couldn't symfony-cli *depend* on the repo defining the standalone checker ?

**Comment by fabpot** [comment]
Sure @stof, that's "possible", but is it worth it?

**Comment by Neirda24** [comment]
I'm torn between the two solutions. On a day to day basis that would be nice indeed. But during CI process we don't always need the symfony cli. I actually never need it a context of a CI (which is where IMO it is the most useful). As such we either have to depend on a specific dedicated tool or a multi usage one.. as such I would prefer to depend on the specific one.

**Comment by stof** [comment]
Well, the security-advisories database was put in https://github.com/FriendsOfPHP to avoid making it considered as being symfony-specific.
If the symfony-cli is the only way to check a project against that database (rather than having a standalone dedicated CLI tool), that would still tie the project to symfony.

**Comment by mbabker** [comment]
I think I actually lean more toward a 👎  on this than a 👍 .

The security checker is a useful tool for any PHP project and is much less aggressive than https://github.com/Roave/SecurityAdvisories, making it a part of the Symfony binary gives the initial perception that the tool is only useful for Symfony projects (even if the CLI does provide other features that are useful to PHP projects as a whole and not just Symfony).

**Comment by fabpot** [comment]
Ok, like expected, "you" want the cake and eat it too :) Let me think about it ;)

**Comment by fabpot** [comment]
See #46
