### ISSUE TITLE
Connections to the webserver refused since 5.8.13 update

### ISSUE THREAD

**Issue by SBougain** [symfony-cli/symfony-cli#456]
Hi ! 
I updated symfony-cli this morning from 5.8.12 to 5.8.13. I ran `symfony serve -d` on my development server and could not reach any pages. I got the "Connection was refused" from Firefox and Edge said "ERR_HTTP2_PROTOCOL_ERROR". I tried emptying my cache, rebooting the server but nothing worked until I downgraded symfony-cli to 5.8.12. Nothing was shown on the `symfony server:log`.
My development server is running on a raspberry pi 4 with Ubuntu 20.04.6

**Comment by potievdev** [comment]
The same problem. Server fails with error `2024/03/23 14:26:39 http2: panic serving 127.0.0.1:50430: runtime error: index out of range [0] with length 0`

**Comment by shersant** [comment]
Hello I have the same problem the web server start correctly but when I go to my browser on 127.0.0.1:8000 the server crash

**Comment by potievdev** [comment]
@fabpot  last release looks like broken. I suggest this changes may related with problem
<img width="1437" alt="Screenshot 2024-03-23 в 14 40 39" src="https://github.com/symfony-cli/symfony-cli/assets/7069932/4c58439c-bdeb-4bb0-96bd-6c02a6670345">

**Comment by dsands** [comment]
> Hi ! I updated symfony-cli this morning from 5.8.12 to 5.8.13. I ran `symfony serve -d` on my development server and could not reach any pages. I got the "Connection was refused" from Firefox and Edge said "ERR_HTTP2_PROTOCOL_ERROR". I tried emptying my cache, rebooting the server but nothing worked until I downgraded symfony-cli to 5.8.12. Nothing was shown on the `symfony server:log`. My development server is running on a raspberry pi 4 with Ubuntu 20.04.6

I'm probably breaking protocol here and I apologize, but I'm having a hard time figuring out how to downgrade to 5.8.12 using Homebrew... I'm dead in the water with a deadline looming. Thanks in advance and again, sorry if my desperation is leading me to go off the reservation.

**Comment by potievdev** [comment]
Hello! You can not downgrade using homebrew to 5.8.12. But you can
downgrade manually. For it open releases page on github and find release
5.8.12 and below it you can see Assets tab. There you can download the
binary file of symfony cli. I am using MacOS  and for me appropriate
https://github.com/symfony-cli/symfony-cli/releases/download/v5.8.12/symfony-cli_darwin_all.tar.gz
. Unpack it and move the symfony binary to /usr/local/bin/symfony . First
time you run a binary file OS will block the program, open Settings and
navigate to Privacy and Security tab and give permission to run symfony-cli
and rerun symfony. I hope this helps.

**Comment by fabpot** [comment]
New release soon available. See https://github.com/symfony-cli/symfony-cli/actions/runs/8403074376/job/23013182483
