### ISSUE TITLE
Allow to server:start without workers

### ISSUE THREAD

**Issue by yguedidi** [symfony-cli/symfony-cli#459]
Maybe add a `--no-workers` option?

This is an alternative solution to #399 for CI environments, where building may already be done, watching files may not be needed, and consuming message be done in another way like by using CI services.

**Comment by fabpot** [comment]
That's a good idea. Can you work on a PR? (and maybe close #399)

**Comment by yguedidi** [comment]
@fabpot I never worked with Go, but yes I planned to try this week-end, want to write my first code lines in Go!
Any guidance on how to do the setup and run tests? I plan to use VS Code

**Comment by fabpot** [comment]
VS code has support for Go, so that's all you need.
