### ISSUE TITLE
Add an option to specify the ip address where the server will be running

### ISSUE THREAD

**Issue by steve-todorov** [symfony-cli/symfony-cli#47]
Hi,

I'm migrating some older 3.4 applications where we used to have `Symfony\Bundle\WebServerBundle\WebServerBundle`  for local development. We use docker and hence were using the `php bin/console server:run 0.0.0.0:8000` option so that the application was actually visible from outside the container. 

Just a reminder - `127.0.0.1` inside a container is essentially a loopback to the container itself. 
This means in order to actually open the web server you need to either use an http proxy application (i.e. nginx) that proxy-forwards requests or be physically inside the container.. which probably won't happen until the Matrix 5 comes out. :D 

So, back to the topic - after upgrading to 5.4 and using the `symofny cli` I noticed it is currently lacking the `run` option which means running your dev environment using Docker will not work. Are there any plans to add this feature back or maybe a workaround that does not involve running yet another server?

I think it would be fine to have a big red-colored warning message which states "running this in production is a terrible idea".

**Comment by fabpot** [comment]
Closing for now. If someone wants to work on it, I started a PR here #87
