### ISSUE TITLE
Completion of symfony console

### ISSUE THREAD

**Issue by flkasper** [symfony-cli/symfony-cli#481]
It is currently not possible to use the console completion of Symfony in combination with symfony-cli.

As far as I understand and assume, the completion of the symfony-cli in "symfony console" should be replaced by that of the console.

Likewise with symfony composer (is also just a symfony cli app)

**Comment by tucksaun** [comment]
Hi there,

This is something I'm currently working on and unfortunately this is not trivial as bash, zsh and fish don't have the same logic to do this. Currently I am blocked with fish support.
