### ISSUE TITLE
local:server:start hangs for ±3 minutes before web server is booted

### ISSUE THREAD

**Issue by ostrolucky** [symfony-cli/symfony-cli#496]
Best visualized on following screenshot
![image](https://github.com/symfony-cli/symfony-cli/assets/496233/adabbce9-bea1-48e4-807a-533b30f4af1d)

as you can see in logs and terminal timeline on the right side, boot up process hanged between 12:35:00 and 12:37:48 (and web server port was not open as I kept checking in background). At 12:37:48, web server started listening to connections.

It used to work quite quickly before, not sure what changed.

**Comment by kbond** [comment]
I recently had the same issue. I think it started after a symfony-cli update I made while I had an server running. A reboot fixed the issue.
