### ISSUE TITLE
The --webapp flag cannot be used with --no-git

### ISSUE THREAD

**Issue by emodric** [symfony-cli/symfony-cli#498]
Hi!

What is the reasoning behind not allowing disabling `git init` when using `--webapp` switch?

My usecase locally is to not specify the email address used for my git repos globally. Instead, I manually run git config on the repo itself to specify the email, since I use different email addresses on different repos.

With this setup, I cannot use `symfony new test --webapp`, becuase the command fails with:

```
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: no email was given and auto-detection is disabled
                   
  exit status 128  
```

The only thing I can see that is happening is that `--webapp` creates a new commit, but I don't really need that. I just want a webapp project witout a git repo, which will I initialize later myself.

**Comment by tucksaun** [comment]
No particular reason expect if used to be easier to managed in the code and that it is required for SymfonyCloud or Upsun projects.
See #499

**Comment by emodric** [comment]
Thanks @tucksaun !
