### ISSUE TITLE
scoop installed composer shows warning

### ISSUE THREAD

**Issue by jraller** [symfony-cli/symfony-cli#50]
I installed symfony-cli and composer with scoop because the `self:update` command was removed from symfony-cli. When I run `symfony composer` it shows the

>"WARNING: Unable to find Composer, downloading one. It is recommended to install Composer yourself at https://getcomposer.org/download/"

But then it appears to run the composer that was installed by scoop. I say this because I'm not seeing a download progress, and there isn't a delay between the warning and Composer's output. If it is downloaded, it isn't retained because the same message is repeated the next time.

symfony-cli version 5.1.0  (via scoop)
composer 2.2.4 (via scoop)

**Comment by fabpot** [comment]
Can you investigate what is happening and see if you can propose a fix?

**Comment by fabpot** [comment]
#43 might be a duplicate?

**Comment by jraller** [comment]
It appears that this is no longer an issue with version 5.3.0 of symfony-cli and version 2.2.5 of composer.
