### ISSUE TITLE
Symfony not detecting my docker containers

### ISSUE THREAD

**Issue by pmishev** [symfony-cli/symfony-cli#518]
I have docker running with several containers using `docker compose`, however none of them show in the Symfony toolbar:
![image](https://github.com/user-attachments/assets/14084adf-8435-42fb-9b54-257b78a3160d)

Also running `symfony var:export --debug --multiline` doesn't list any docker containers, nor env variables that should have been set by docker.

Maybe the issue is docker-side, but I have no idea how to further diagnose the problem.
I'm running Docker Desktop.
`/opt/docker-desktop/bin/com.docker.diagnose check` shows no fatal errors
```
$ docker version
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:00 2024
 OS/Arch:           linux/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.34.2 (167172)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:15 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by Kocal** [comment]
Could it be related to https://github.com/symfony-cli/symfony-cli/issues/285 (DOCKER_HOST env var issue)

**Comment by pmishev** [comment]
Indeed it was, thank you!

Adding `export DOCKER_HOST=unix://$HOME/.docker/desktop/docker.sock` in my .bashrc fixed the problem.
There should really be at least some indication of the problem, like an error message that `docker.sock` is not found when you run `symfony var:export --debug` maybe with a suggestion why.

**Comment by tucksaun** [comment]
The socket detection path is not part of the Symfony CLI code but directly Docker's one. I'll see what we can do but as stated [previously](https://github.com/symfony-cli/symfony-cli/issues/285#issuecomment-1477763918), Docker explicitly says that in such case one has to export DOCKER_HOST so I'm not sure I can do it so easily 😕

Regarding the `--debug` flag: the debug information are already showed when one using the `-vvv` flag, but it's true this flag documentation is mentioning "Debug Docker support" so I'll look into it.

**Comment by tucksaun** [comment]
See https://github.com/symfony-cli/symfony-cli/pull/519 for connection error logging

**Comment by tucksaun** [comment]
See #520 for a fix attempt
