### ISSUE TITLE
PR #494 broke Docker startup with `ENTRYPOINT ["symfony", "server:start", "--no-tls", "--port=80"]`

### ISSUE THREAD

**Issue by powernic** [symfony-cli/symfony-cli#523]
The recent pull request #494, which changes the default behavior to only listen on 127.0.0.1, has caused issues when running Symfony CLI in a Docker container. Specifically, the following `ENTRYPOINT` command no longer works as expected:

```Dockerfile
ENTRYPOINT ["symfony", "server:start", "--no-tls", "--port=80"]
```

### Steps to Reproduce:  
Create a Dockerfile with the following content:
```
FROM php:8.2-fpm-alpine3.17
RUN   curl -s https://get.symfony.com/cli/installer | bash \
	&& mv /root/.symfony5/bin/symfony /usr/local/bin/symfony
WORKDIR /var/www/html
ENTRYPOINT ["symfony", "server:start", "--no-tls", "--port=80"]
```
Build and run the Docker container.
Attempt to access the Symfony server from outside the container.
### Expected Behavior: 
The Symfony server should be accessible from outside the Docker container.  Actual Behavior: The server is not accessible because it only listens on 127.0.0.1.  
### Proposed Solution:
 Allow specifying the address to listen on via an environment variable or command-line option, or revert the default behavior to listen on all addresses (0.0.0.0).  

### Additional Context: 
This issue affects users who rely on Docker for their development and deployment workflows. The change in default behavior has introduced a breaking change for these users.

**Comment by tucksaun** [comment]
Yes this is inconvenient...
I'm going to work on a PR to add some configuration allowing to revert to the previous configuration.

I'm also going to see if we can detect the docker context somehow and enable this behavior by default in such context.

**Comment by check24-danielpaschsannapiu** [comment]
AS discussed here. It's probably the best solution to have a cli flag for the listen address like most web servers. 

Keep port as a "legacy" flag to not break current usage, but let the listen address be able to overwrite it. 

https://github.com/symfony-cli/symfony-cli/commit/e697eb86cee9289997d405945071d07e356160c8#commitcomment-147803424

**Comment by mbraun81** [comment]
Is there already a solution to the problem? I've been struggling with the identification for 2 1/2 days now because my colleagues said that everything was working for them, but they probably didn't rebuild the image either and so the Symfony update was in their system. I develop under Windows 11 with an Ubuntu WSL in which I run the docker. This way I can make sure that all my colleagues are developing with the same system and if I can no longer reach the web server, it's really bad for further development.

**Comment by check24-danielpaschsannapiu** [comment]
Downgrade symfony-cli to [v5.10.2](https://github.com/symfony-cli/symfony-cli/releases/tag/v5.10.2)

**Comment by powernic** [comment]
> Is there already a solution to the problem? I've been struggling with the identification for 2 1/2 days now because my colleagues said that everything was working for them, but they probably didn't rebuild the image either and so the Symfony update was in their system. I develop under Windows 11 with an Ubuntu WSL in which I run the docker. This way I can make sure that all my colleagues are developing with the same system and if I can no longer reach the web server, it's really bad for further development.

Here's a solution that should work for Alpine Linux. Add the following lines to your Dockerfile to install the Symfony CLI directly:
```
ENV SYMFONY_VERSION=5.10.2
RUN  curl -o symfony-cli.apk -L https://github.com/symfony-cli/symfony-cli/releases/download/v${SYMFONY_VERSION}/symfony-cli_${SYMFONY_VERSION}_x86_64.apk && \
     apk add --allow-untrusted symfony-cli.apk
```

**Comment by mbraun81** [comment]
I have now rebuilt the Dockerfile so that I use an Apache instead of the Symfony web server.

**Comment by tucksaun** [comment]
> > Is there already a solution to the problem? I've been struggling with the identification for 2 1/2 days now because my colleagues said that everything was working for them, but they probably didn't rebuild the image either and so the Symfony update was in their system. I develop under Windows 11 with an Ubuntu WSL in which I run the docker. This way I can make sure that all my colleagues are developing with the same system and if I can no longer reach the web server, it's really bad for further development.
> 
> Here's a solution that should work for Alpine Linux. Add the following lines to your Dockerfile to install the Symfony CLI directly:
> 
> ```
> ENV SYMFONY_VERSION=5.10.2
> RUN  curl -o symfony-cli.apk -L https://github.com/symfony-cli/symfony-cli/releases/download/v${SYMFONY_VERSION}/symfony-cli_${SYMFONY_VERSION}_x86_64.apk && \
>      apk add --allow-untrusted symfony-cli.apk
> ```

I would recommend to use the `COPY —from=ghcr.io/symfony-cli/symfony-cli:5.10.2 […]` syntax instead.

> Is there already a solution to the problem? I've been struggling with the identification for 2 1/2 days now because my colleagues said that everything was working for them, but they probably didn't rebuild the image either and so the Symfony update was in their system. I develop under Windows 11 with an Ubuntu WSL in which I run the docker. This way I can make sure that all my colleagues are developing with the same system and if I can no longer reach the web server, it's really bad for further development.

In a Docker environment, you should be able to workaround the issue with some port mapping, no?

**Comment by mbraun81** [comment]
I just realized that my solution works perfectly for Docker, but not directly for the Ubuntu WSL, as I am running multiple Linux systems as WSL. The issue is that they all share the same IP address, so I have to make the Apache listen on a different port. The update is really annoying, if I may say so.
