### ISSUE TITLE
the `check-requirements` command does not properly check the required min PHP version for Symfony 6 or 7

### ISSUE THREAD

**Issue by stof** [symfony-cli/symfony-cli#536]
https://github.com/symfony-cli/symfony-cli/blob/4c51f18f33bc9bba4efa54b26e01a4a99107cdd8/commands/data/check-requirements.php#L372-L374 does not contain the requirements for 6.x or 7.x.

Also, if there is no installed version of Symfony yet (i.e. when using that command before `symfony new`), the CLI should probably assume the highest known version of Symfony (or support a flag) instead of assuming Symfony 3.x

**Comment by fabpot** [comment]
See https://github.com/symfony/requirements-checker/pull/48
