### ISSUE TITLE
Symfony web serveur not accessible from outside of docker container / --allow-all-ip

### ISSUE THREAD

**Issue by xenatis** [symfony-cli/symfony-cli#540]
Hi,
Today, after a full rebuild of an old Docker image, impossible to access the Symfony web server from the host anymore.

After some research I found that I have to use `--allow-all-ip` or `--listen-ip 0.0.0.0` parameter when runing `symfony server:start` to make the server accessible from outside of the container.

Did the last updates of Symfony CLI change the default dehavior of `symfony server:start` ?
Did I miss some changelog ?

Context:
Symfony CLI v5.10.4
Docker image php8.2-fpm

**Comment by tucksaun** [comment]
This is the case since [v5.10.3](https://github.com/symfony-cli/symfony-cli/releases/tag/v5.10.3).

The flags have been introduced in v5.10.4 to partially revert this and the Docker image has been fixed at the same time (see https://github.com/symfony-cli/symfony-cli/pull/525 for more details)

**Comment by xenatis** [comment]
Thanks for the answer.
I’ll be more careful when reading change logs.
