### ISSUE TITLE
[symfony-cli] Add symfony command tests:run for --webapp flag

### ISSUE THREAD

**Issue by malakanov** [symfony-cli/symfony-cli#549]
When we create a new symfony app with flag `--webapp` by calling

`symfony new my_project_directory --version="7.2.x-dev" --webapp `(see [https://symfony.com/doc/current/setup.html](https://github.com/symfony/symfony/issues/url))

the `symfony/test-pack` component is installed along with it.

After all for execute tests we need run command `php bin/phpunit`

It might be worth adding a feature to symfony command tests:run which will execute php bin/phpunit for the case of new creation application with flag --webapp

**For example**

Run all tests of the application which call php bin/phpunit

`symfony console tests:run`

**Comment by tucksaun** [comment]
Hi there!

Isn't running `symfony php bin/phpunit` enough?

**Comment by malakanov** [comment]
> When we create a new symfony app with flag `--webapp` by calling
> 
> `symfony new my_project_directory --version="7.2.x-dev" --webapp `(see [https://symfony.com/doc/current/setup.html](https://github.com/symfony/symfony/issues/url))
> 
> the `symfony/test-pack` component is installed along with it.
> 
> After all for execute tests we need run command `php bin/phpunit`
> 
> It might be worth adding a feature to symfony command tests:run which will execute php bin/phpunit for the case of new creation application with flag --webapp
> 
> **For example**
> 
> Run all tests of the application which call php bin/phpunit
> 
> `symfony tests:run`

Sorry, for my mistake, I mean `symfony console tests:run`

**Comment by tucksaun** [comment]
`symfony console` is only a wrapper around the current application `bin/console`.
we don't really have control over what is done once `bin/console` is run`

so `tests:run` would need to be defined in your own application or in any of your vendor bundles but not in Symfony CLI.

**Comment by malakanov** [comment]
> `symfony console` is only a wrapper around the current application `bin/console`. we don't really have control over what is done once `bin/console` is run`
> 
> so `tests:run` would need to be defined in your own application or in any of your vendor bundles but not in Symfony CLI.

Hi! Why i can call `symfony console doctrine` and not can't call `symfony console `

**Comment by tucksaun** [comment]
I don't understand your question. Both commands are supported.
