### ISSUE TITLE
TLS certificate stop working

### ISSUE THREAD

**Issue by darielvicedo** [symfony-cli/symfony-cli#64]
After updating to the new Symfony-CLI the locally installed TLS certificate stop working. Trying to reinstall with --force and --renew flags and still not working.
In both cases, the output is:
```sh
[OK] The local Certificate Authority is installed and trusted
```

---

**SO:** Ubuntu 21.04 over WSL on Windows 10
**PHP:** 8.0.14
**Symfony-CLI:** 5.2.2

**Comment by fabpot** [comment]
The new CLI will use a new TLS, so you indeed need to run `ca:install` again. You might need to stop and start your browser (maybe reboot on Windows).
