### ISSUE TITLE
Incorrect colors when using git bash in PhhStorm

### ISSUE THREAD

**Issue by Maxime-p** [symfony-cli/symfony-cli#68]
When I use symfony cli commands in git bash : No problem
When I use it in PhpStorm with git bash as terminal : 
![image](https://user-images.githubusercontent.com/43859895/151006431-8a135735-fb30-4091-a93c-c8eb4e1d06c3.png)

**Comment by michitheonlyone** [comment]
I installed Ansicon (as described in the above post) and it worked for me:
[http://adoxa.altervista.org/ansicon/](http://adoxa.altervista.org/ansicon/)
[https://github.com/adoxa/ansicon](https://github.com/adoxa/ansicon)

Install it in e.g. `c:\Program Files\Ansicon` and then change terminal shell path inside PHPStorm to:
`"C:\Program Files\Ansicon\ansicon.exe" "C:\Program Files\Git\bin\bash.exe" --login -i`
After this it worked also fine in other Terminals like CMD.

**Comment by Maxime-p** [comment]
> I installed Ansicon (as described in the above post) and it worked for me: http://adoxa.altervista.org/ansicon/ https://github.com/adoxa/ansicon
> 
> You need the following files in your `C:\Program Files\Ansicon\` directory:
> 
>     * ANSI32.dll
> 
>     * ANSI64.dll
> 
>     * ansicon.exe
> 
> 
> Install it in e.g. `c:\Program Files\Ansicon` and then change terminal shell path inside PHPStorm to: `"C:\Program Files\Ansicon\ansicon.exe" "C:\Program Files\Git\bin\bash.exe" --login -i` After this it worked also fine in other Terminals like CMD.

Yes, I know but is this a long term fix or is there a solution that can be brought to symfony cli

**Comment by fabpot** [comment]
Closing as there is a solution. If anyone has a better idea to "fix" Symfony CLI, feel free to open a PR, I think on symfony-cli/terminal where the code is hosted for this part.
