### ISSUE TITLE
Sign release artifacts using sigstore/cosign

### ISSUE THREAD

**Issue by hslatman** [symfony-cli/symfony-cli#69]
This issue is about signing the release artifacts, being the `checksums.txt` and/or the compiled binaries, using [sigstore/cosign](https://github.com/sigstore/cosign). 

Despite what its description says about signing containers, it also supports signing binary blobs. Since `symfony-cli` binaries are created using GoReleaser and the fact that [GoReleaser supports signing with cosign since v0.176.0](https://carlosbecker.com/posts/goreleaser-cosign/), adding this to `symfony-cli` will probably not be hard.

Users of the CLI can (manually) verify that the binary is signed using the correct private key.

**Comment by fabpot** [comment]
Would you like to work on a PR? I suppose this is a matter of adding the correct config in the goreleaser.yml file? I will then set then the needed env vars to make it work

**Comment by hslatman** [comment]
Yes, I will give this a go!

**Comment by hslatman** [comment]
@fabpot: I made some progress here: https://github.com/hslatman/symfony-cli/releases/tag/v5.3.0-exp-sign-4. Currently only the `checksums.txt` file is signed (the default). Verification looks like this:

```console
$ COSIGN_EXPERIMENTAL=1 cosign verify-blob --signature checksums.txt.sig checksums.txt
tlog entry verified with uuid: "b36fd360497840c4b3b5a8fae09d73423a02b1e4cd52f318e04537eb88bf5faf" index: 1236870
Verified OK
```

Alternatively:

```console
$ cosign verify-blob --cert checksums.txt.pem --signature checksums.txt.sig checksums.txt
Verified OK
```

A user then should perform something like the following in a directory containing the downloaded artifacts:

```console
$ sha256sum --ignore-missing -c checksums.txt
symfony-cli_next_i386.deb: OK
symfony-cli_linux_arm64.tar.gz.sbom: OK
symfony-cli-next.x86_64.rpm: OK
...
```

The setup is based on https://github.com/goreleaser/supply-chain-example. This uses the (currently) experimental `keyless` signing method of cosign: https://github.com/sigstore/cosign/blob/main/KEYLESS.md. The alternative is to use a fixed public/private key pair, which is what is used in the example I linked above.

As mentioned, currently only `checksums.txt` is signed. After verifying the signature on `checksums.txt` a user needs to check that the sha256 hash matches the ones in `checksums.txt`. It's also possible to sign the binaries instead (or in addition to `checksums.txt`), which could then be verified directly using `cosign`. I think it may make the user experience a little easier, so I think it's good to do. WDYT?

SBOMs for all archives are also included in SPDX format. Is this something you want, or should I remove it? It's also possible to create SBOMs for the binaries directly, packages, etc. More information about this is here: https://goreleaser.com/customization/sbom/

I temporarily disabled the `gomod proxy` option of GoReleaser, because proxying didn't work with my custom tag while using this repo. Enabling that again should make it work here. It's generally good to embed the information gained in this way: https://goreleaser.com/customization/gomod/

Another change I made: `secrets.GH_PAT` -> `secrets.GITHUB_TOKEN`. This should probably also be reverted, as I assume there's a PAT with limited permissions in that env var?

All of this is powered by GoReleaser and based on his example in https://github.com/goreleaser/supply-chain-example. Thank you, @caarlos0!

**Comment by caarlos0** [comment]
> Another change I made: `secrets.GH_PAT` -> `secrets.GITHUB_TOKEN`. This should probably also be reverted, as I assume there's a PAT with limited permissions in that env var?

if you write to repos outside the current one, yes... you could set another token just for that (e.g. `homebrew.tap` accepts a token which can be another environment variable...
