### ISSUE TITLE
License file provided but no copyright/license notices

### ISSUE THREAD

**Issue by Exagone313** [symfony-cli/symfony-cli#7]
Hi,

The AGPL license has been included in the repository (and the other repositories as well), but there is no copyright or license notices. The code might still be proprietary.

You can find guidelines on how to use the GNU licenses [here](https://www.gnu.org/licenses/gpl-howto.html).

You could at the very least include these in the README, but it's more clear to prepend each file with the statement.

**Comment by fabpot** [comment]
Fixed now.
