### ISSUE TITLE
How to install on apk based system

### ISSUE THREAD

**Issue by Neirda24** [symfony-cli/symfony-cli#70]
Hi.

Just saw the message to use this new open-source version of the symfony cli.
Although on this page https://symfony.com/download it states how to install it for apt / yum based linux systems.
On alpine containers neither exists. Is there something I'm missing ?

Thanks

**Comment by fabpot** [comment]
You can download apk files on the release page directly: https://github.com/symfony-cli/symfony-cli/releases/latest
I've just updated the symfony.com Download page to mention these APK packages.

**Comment by Neirda24** [comment]
Thanks.
