### ISSUE TITLE
Wish: local:php:add command

### ISSUE THREAD

**Issue by pbowyer** [symfony-cli/symfony-cli#80]
On my Windows machine I have 1 version of PHP in the path, and the others stored outside. This means that `symfony local:php:refresh` doesn't detect them.

Currently I edit `C:\Users\Example\.symfony5\php_versions.json` by hand and add the missing versions.

It would be great if there was a built-in command where I can pass a directory path and `symfony-cli` will scan for available PHP versions e.g.
```
symfony local:php:add c:\php8
```

**Comment by fabpot** [comment]
Adding by hand means that you will lose them every time we run the detection again.
Having an add command looks like a useful addition.
Is anyone (you?) willing to implement it?

**Comment by pbowyer** [comment]
Just realised they were being lost as I tried to create a new project. Once added they stay around for commands like `symfony console` to use.

Adding the command might make a good first Go project which appeals to me. I'll add it to my list, but will be a couple of months before I can make a start as I need to finish some other OS contributions first. If anyone else contributes it before me - congrats and thank you 😃

**Comment by henrikac** [comment]
Would this command just save paths to different versions of PHP in some sort of config file?

**Comment by fabpot** [comment]
@henrikac I would store everything in the same file with two sections: one permanent and one that is overridden automatically when needed.

**Comment by pbowyer** [comment]
I'm closing because the effort of adding it, vs putting multiple PHP versions where the script expects, isn't worth it.
