### ISSUE TITLE
Can't get HTTPS server

### ISSUE THREAD

**Issue by Drenore** [symfony-cli/symfony-cli#83]
Hi, 

I'm here today because i start learning symfony, and when i was looking a tutorial on YouTube i tried to launch an HTTPS server with symfony but he doesn't work and made this error. I found lot of articles on the web who say to download a curl to put the path inside php.init, but not working that tell me this : 
![image](https://user-images.githubusercontent.com/84106267/152335623-15b9d637-638d-4622-8017-c92a6716d2e7.png)

Thank to help me !

**Comment by fabpot** [comment]
The error message says that you don't have the right to write the certification. I'm not a Windows user, but I suppose this command should be run as an "admin" user. In any case, nothing we can do on our side.

**Comment by Drenore** [comment]
I know as you can see on top of command consol i'm in admin mode
