### ISSUE TITLE
Command "check:security" does not exist.

### ISSUE THREAD

**Issue by 94noni** [symfony-cli/symfony-cli#9]
After a clean install of this new tool for macOS via Homebrew,
When running this https://symfony.com/doc/current/setup.html#checking-security-vulnerabilities:

```bash
symfony check:security
Command "check:security" does not exist.
```

**Comment by wouterj** [comment]
I cannot reproduce on v4.27.4 on Linux.

```
~/p/l/s/sf-5.4 > symfony check:security
Symfony Security Check Report
=============================

No packages have known vulnerabilities.

Note that this checker can only detect vulnerabilities that are referenced in the security advisories database.
Execute this command regularly to check the newly discovered vulnerabilities.

```

**Comment by 94noni** [comment]
On macOS 12.1 (21C52)

```bash
symfony version
Symfony CLI version 5.0.4 (c) 2017-2022 Symfony SAS (2022-01-01T10:25:37Z - stable)
```

**Comment by fabpot** [comment]
Indeed, the command does not exist in the new version of the CLI, you should use https://github.com/fabpot/local-php-security-checker instead.

**Comment by 94noni** [comment]
@fabpot Ok I see, perhaps doc should be updated accordingly :)
thx !

**Comment by fabpot** [comment]
Can you create an issue/PR on the docs?
