### ISSUE TITLE
Blackfire integration - Enable BLACKFIRE_AGENT_SOCKET support?

### ISSUE THREAD

**Issue by fbourigault** [symfony-cli/symfony-cli#92]
I'm trying to get blackfire agent as a docker service instead of using my OS installed blackfire-agent.

I installed the https://github.com/symfony/recipes/tree/master/blackfireio/blackfire-symfony-meta/1.0 recipe but PHP probe still want to connect to unix socket.

According to https://blackfire.io/docs/php/configuration, I can use the `BLACKFIRE_AGENT_SOCKET` env var to configure the PHP probe.

I looked into the code and found a reference to `BLACKFIRE_AGENT_SOCKET` env var: https://github.com/symfony-cli/symfony-cli/blob/48ca923fa3adc2e725788626f02501dff52ddc6a/envs/envs.go#L262-L266.

Is it time to enable the integration using `BLACKFIRE_AGENT_SOCKET` env var?

**Comment by fbourigault** [comment]
I will stick with my global agent until supported in local server because of the random port.

**Comment by lolautruche** [comment]
Host agent is perfectly fine, indeed 👍

**Comment by fbourigault** [comment]
Yes, I’m just trying to ease project onboarding :)
