### ISSUE TITLE
From the "The Fast Track" missing --docker flag

### ISSUE THREAD

**Issue by ChrisRiddell** [symfony-cli/symfony-cli#94]
The initializing-the-project page from The Fast Track book the command shown an error for a missing -docker flag

https://symfony.com/doc/current/the-fast-track/en/3-zero.html#initializing-the-project
`symfony new guestbook --version=6.0 --php=8.1 --webapp --docker --cloud`

`Incorrect usage: flag provided but not defined: -docker`

**Comment by fabpot** [comment]
Are you using the latest version of the CLI? And the one from this repository (not the "old" non-Open-Source one)?

**Comment by ChrisRiddell** [comment]
I’m using the one that’s installed via brew version 5.3.4

**Comment by fabpot** [comment]
What `symfony version` outputs?

**Comment by ChrisRiddell** [comment]
`Symfony CLI version v4.28.1 (2022-01-10T10:41:34+0000 - stable)`
But brew reports `symfony-cli/tap/symfony-cli 5.3.4 is already installed`

Looks like somehow I have ended up with both versions on the system.

**Comment by fabpot** [comment]
Closing then. Just remove the old binary.

**Comment by ChrisRiddell** [comment]
Note for anyone who runs into this remove old binary `rm '/usr/local/bin/symfony'` then run `brew link symfony-cli`
