### ISSUE TITLE
Is there any way to overwrite the PHP-FPM settings?

### ISSUE THREAD

**Issue by marphi** [symfony-cli/symfony-cli#96]
From time to time I've got warning:
```
[PHP-FPM    ] Feb 18 14:40:51 |WARNING| FPM    [pool www] server reached pm.max_children setting (5), consider raising it
```
And then my server is not responding. I have to restart it manually.

Is there any way to deliver own `www.conf` file for php-fpm?

**Comment by fabpot** [comment]
No, there is no current way.
Not sure it would make sense for a dev server to make this configurable.

**Comment by marphi** [comment]
I agree @fabpot. My primary issue was located elsewhere. I did too heavy computing on `kernel.terminate` event. Now I don't have needs to increase this options.

**Comment by Claod44** [comment]
So how to fix that  then ... 

 [ERROR] PHP-FPM failed to start:
 [pool www] please specify user and group other than root
 FPM initialization failed



  PHP server exited unexpectedly: command "PHP-FPM" failed early: exit status 78




when symfony cli is  ignoring www.conf ?

**Comment by tucksaun** [comment]
@Claod44 can you try by running Symfony CLI as a standard user instead of the root user?

**Comment by Claod44** [comment]
I did, problem is : port 80 root reserved x')

**Comment by tucksaun** [comment]
Symfony CLI is not really intended to run as root.
One of the main reason is that this will easily lead to privilege issues on your files.

But also, Symfony CLI has been created to facilitate development experience where tons of things can change, web port is one them, and help you not rely on it, so the port is not guaranteed to be 8080 or the one you specify (this is why the help says "preferred").

But if you need something more stable (which we wanted as well when creating the tool ;)) you can try to use the local domains: https://symfony.com/doc/current/setup/symfony_server.html#local-domain-names.
It can help you having memorable domain names for your project without the need to specify any port number.

**Comment by fabpot** [comment]
> > No, there is no current way. Not sure it would make sense for a dev server to make this configurable.
> 
> [@fabpot](https://github.com/fabpot) Any chance to increase `pm.max_children`? We are talking about a tool which runs on developer's hardware, so memory shouldn't be an issue. I get this error all the time when running my Contao sites locally. Something around ~ 100 should do it, according to https://spot13.com/pmcalculator/

See #563
